#include "testmodel.h"

TestModel::TestModel(QObject *parent) :
    QAbstractListModel(parent)
{
    countries << "Abbey Wood - ABW";
    countries << "Aber - ABE";
    countries << "Abercynon - ACY";
    countries << "Aberdare - ABA";
    countries << "Aberdeen - ABD";
    countries << "Aberdour - AUR";
    countries << "Aberdovey - AVY";
    countries << "Abererch - ABH";
    countries << "Abergavenny - AGV";
    countries << "Abergele & Pensarn - AGL";
    countries << "Aberystwyth - AYW";
    countries << "Accrington - ACR";
    countries << "Achanalt - AAT";
    countries << "Achnasheen - ACN";
    countries << "Achnashellach - ACH";
    countries << "Acklington - ACK";
    countries << "Acle - ACL";
    countries << "Acocks Green - ACG";
    countries << "Acton Bridge (Cheshire) - ACB";
    countries << "Acton Central - ACC";
    countries << "Acton Main Line - AML";
    countries << "Adderley Park - ADD";
    countries << "Addiewell - ADW";
    countries << "Addlestone - ASN";
    countries << "Adisham - ADM";
    countries << "Adlington (Cheshire) - ADC";
    countries << "Adlington (Lancs) - ADL";
    countries << "Adwick - AWK";
    countries << "Aigburth - AIG";
    countries << "Ainsdale - ANS";
    countries << "Aintree - AIN";
    countries << "Airbles - AIR";
    countries << "Airdrie - ADR";
    countries << "Albany Park - AYP";
    countries << "Albrighton - ALB";
    countries << "Alderley Edge - ALD";
    countries << "Aldermaston - AMT";
    countries << "Aldershot - AHT";
    countries << "Aldrington - AGT";
    countries << "Alexandra Palace - AAP";
    countries << "Alexandra Parade - AXP";
    countries << "Alexandria - ALX";
    countries << "Alfreton - ALF";
    countries << "Allens West - ALW";
    countries << "Alloa - ALO";
    countries << "Alness - ASS";
    countries << "Alnmouth - ALM";
    countries << "Alresford (Essex) - ALR";
    countries << "Alsager - ASG";
    countries << "Althorne (Essex) - ALN";
    countries << "Althorpe - ALP";
    countries << "Altnabreac - ABC";
    countries << "Alton - AON";
    countries << "Altrincham - ALT";
    countries << "Alvechurch - ALV";
    countries << "Ambergate - AMB";
    countries << "Amberley - AMY";
    countries << "Amersham - AMR";
    countries << "Ammanford - AMF";
    countries << "Ancaster - ANC";
    countries << "Anderston - AND";
    countries << "Andover - ADV";
    countries << "Anerley - ANZ";
    countries << "Angel Road - AGR";
    countries << "Angmering - ANG";
    countries << "Annan - ANN";
    countries << "Anniesland - ANL";
    countries << "Ansdell & Fairhaven - AFV";
    countries << "Appleby - APP";
    countries << "Appledore (Kent) - APD";
    countries << "Appleford - APF";
    countries << "Appley Bridge - APB";
    countries << "Apsley - APS";
    countries << "Arbroath - ARB";
    countries << "Ardgay - ARD";
    countries << "Ardlui - AUI";
    countries << "Ardrossan Harbour - ADS";
    countries << "Ardrossan South Beach - ASB";
    countries << "Ardrossan Town - ADN";
    countries << "Ardwick - ADK";
    countries << "Argyle Street - AGS";
    countries << "Arisaig - ARG";
    countries << "Arlesey - ARL";
    countries << "Armadale (West Lothian) - ARM";
    countries << "Armathwaite - AWT";
    countries << "Arnside - ARN";
    countries << "Arram - ARR";
    countries << "Arrochar & Tarbet - ART";
    countries << "Arundel - ARU";
    countries << "Ascot (Berks) - ACT";
    countries << "Ascott-under-Wychwood - AUW";
    countries << "Ash - ASH";
    countries << "Ash Vale - AHV";
    countries << "Ashburys - ABY";
    countries << "Ashchurch for Tewkesbury - ASC";
    countries << "Ashfield - ASF";
    countries << "Ashford International - AFK";
    countries << "Ashford International (Eurostar) - ASI";
    countries << "Ashford (Surrey) - AFS";
    countries << "Ashley - ASY";
    countries << "Ashtead - AHD";
    countries << "Ashton-under-Lyne - AHN";
    countries << "Ashurst (Kent) - AHS";
    countries << "Ashurst New Forest - ANF";
    countries << "Ashwell & Morden - AWM";
    countries << "Askam - ASK";
    countries << "Aslockton - ALK";
    countries << "Aspatria - ASP";
    countries << "Aspley Guise - APG";
    countries << "Aston - AST";
    countries << "Atherstone - ATH";
    countries << "Atherton (Manchester) - ATN";
    countries << "Attadale - ATT";
    countries << "Attenborough - ATB";
    countries << "Attleborough - ATL";
    countries << "Auchinleck - AUK";
    countries << "Audley End - AUD";
    countries << "Aughton Park - AUG";
    countries << "Aviemore - AVM";
    countries << "Avoncliff - AVF";
    countries << "Avonmouth - AVN";
    countries << "Axminster - AXM";
    countries << "Aylesbury - AYS";
    countries << "Aylesbury Vale Parkway - AVP";
    countries << "Aylesford - AYL";
    countries << "Aylesham - AYH";
    countries << "Ayr - AYR";
    countries << "Bache - BAC";
    countries << "Baglan - BAJ";
    countries << "Bagshot - BAG";
    countries << "Baildon - BLD";
    countries << "Baillieston - BIO";
    countries << "Balcombe - BAB";
    countries << "Baldock - BDK";
    countries << "Balham - BAL";
    countries << "Balloch - BHC";
    countries << "Balmossie - BSI";
    countries << "Bamber Bridge - BMB";
    countries << "Bamford - BAM";
    countries << "Banavie - BNV";
    countries << "Banbury - BAN";
    countries << "Bangor (Gwynedd) - BNG";
    countries << "Bank Hall - BAH";
    countries << "Banstead - BAD";
    countries << "Barassie - BSS";
    countries << "Barbican - ZBB";
    countries << "Bardon Mill - BLL";
    countries << "Bare Lane - BAR";
    countries << "Bargeddie - BGI";
    countries << "Bargoed - BGD";
    countries << "Barking - BKG";
    countries << "Barking Underground - ZBK";
    countries << "Barlaston - BRT";
    countries << "Barming - BMG";
    countries << "Barmouth - BRM";
    countries << "Barnehurst - BNH";
    countries << "Barnes - BNS";
    countries << "Barnes Bridge - BNI";
    countries << "Barnetby - BTB";
    countries << "Barnham - BAA";
    countries << "Barnhill - BNL";
    countries << "Barnsley - BNY";
    countries << "Barnstaple - BNP";
    countries << "Barnt Green - BTG";
    countries << "Barrhead - BRR";
    countries << "Barrhill - BRL";
    countries << "Barrow Haven - BAV";
    countries << "Barrow-in-Furness - BIF";
    countries << "Barrow-Upon-Soar - BWS";
    countries << "Barry - BRY";
    countries << "Barry Docks - BYD";
    countries << "Barry Island - BYI";
    countries << "Barry Links - BYL";
    countries << "Barton-on-Humber - BAU";
    countries << "Basildon - BSO";
    countries << "Basingstoke - BSK";
    countries << "Bat & Ball - BBL";
    countries << "Bath Spa - BTH";
    countries << "Bathgate - BHG";
    countries << "Batley - BTL";
    countries << "Battersby - BTT";
    countries << "Battersea Park - BAK";
    countries << "Battle - BAT";
    countries << "Battlesbridge - BLB";
    countries << "Bayford - BAY";
    countries << "Beaconsfield - BCF";
    countries << "Bearley - BER";
    countries << "Bearsden - BRN";
    countries << "Bearsted - BSD";
    countries << "Beasdale - BSL";
    countries << "Beaulieu Road - BEU";
    countries << "Beauly - BEL";
    countries << "Bebington - BEB";
    countries << "Beccles - BCC";
    countries << "Beckenham Hill - BEC";
    countries << "Beckenham Junction - BKJ";
    countries << "Bedford - BDM";
    countries << "Bedford St Johns - BSJ";
    countries << "Bedhampton - BDH";
    countries << "Bedminster - BMT";
    countries << "Bedworth - BEH";
    countries << "Bedwyn - BDW";
    countries << "Beeston - BEE";
    countries << "Bekesbourne - BKS";
    countries << "Belle Vue - BLV";
    countries << "Bellgrove - BLG";
    countries << "Bellingham - BGM";
    countries << "Bellshill - BLH";
    countries << "Belmont - BLM";
    countries << "Belper - BLP";
    countries << "Beltring - BEG";
    countries << "Belvedere - BVD";
    countries << "Bempton - BEM";
    countries << "Ben Rhydding - BEY";
    countries << "Benfleet - BEF";
    countries << "Bentham - BEN";
    countries << "Bentley (Hants) - BTY";
    countries << "Bentley (South Yorks) - BYK";
    countries << "Bere Alston - BAS";
    countries << "Bere Ferrers - BFE";
    countries << "Berkhamsted - BKM";
    countries << "Berkswell - BKW";
    countries << "Berney Arms - BYA";
    countries << "Berry Brow - BBW";
    countries << "Berrylands - BRS";
    countries << "Berwick (Sussex) - BRK";
    countries << "Berwick-upon-Tweed - BWK";
    countries << "Bescar Lane - BES";
    countries << "Bescot Stadium - BSC";
    countries << "Betchworth - BTO";
    countries << "Bethnal Green - BET";
    countries << "Betws-y-Coed - BYC";
    countries << "Beverley - BEV";
    countries << "Bexhill - BEX";
    countries << "Bexley - BXY";
    countries << "Bexleyheath - BXH";
    countries << "Bicester North - BCS";
    countries << "Bicester Town - BIT";
    countries << "Bickley - BKL";
    countries << "Bidston - BID";
    countries << "Biggleswade - BIW";
    countries << "Bilbrook - BBK";
    countries << "Billericay - BIC";
    countries << "Billingham (Cleveland) - BIL";
    countries << "Billingshurst - BIG";
    countries << "Bingham - BIN";
    countries << "Bingley - BIY";
    countries << "Birchgrove - BCG";
    countries << "Birchington-on-sea - BCH";
    countries << "Birchwood - BWD";
    countries << "Birkbeck - BIK";
    countries << "Birkdale - BDL";
    countries << "Birkenhead Central - BKC";
    countries << "Birkenhead Hamilton Square - BKQ";
    countries << "Birkenhead North - BKN";
    countries << "Birkenhead Park - BKP";
    countries << "Birmingham International - BHI";
    countries << "Birmingham Moor Street - BMO";
    countries << "Birmingham New Street - BHM";
    countries << "Birmingham Snow Hill - BSW";
    countries << "Bishop Auckland - BIA";
    countries << "Bishopbriggs - BBG";
    countries << "Bishops Stortford - BIS";
    countries << "Bishopstone (Sussex) - BIP";
    countries << "Bishopton (Strathclyde) - BPT";
    countries << "Bitterne - BTE";
    countries << "Blackburn - BBN";
    countries << "Blackheath - BKH";
    countries << "Blackhorse Road - BHO";
    countries << "Blackpool North - BPN";
    countries << "Blackpool Pleasure Beach - BPB";
    countries << "Blackpool South - BPS";
    countries << "Blackridge - BKR";
    countries << "Blackrod - BLK";
    countries << "Blackwater - BAW";
    countries << "Blaenau Ffestiniog - BFF";
    countries << "Blair Atholl - BLA";
    countries << "Blairhill - BAI";
    countries << "Blake Street - BKT";
    countries << "Blakedown - BKD";
    countries << "Blantyre - BLT";
    countries << "Blaydon - BLO";
    countries << "Bleasby - BSB";
    countries << "Bletchley - BLY";
    countries << "Bloxwich - BLX";
    countries << "Bloxwich North - BWN";
    countries << "Blundellsands & Crosby - BLN";
    countries << "Blythe Bridge - BYB";
    countries << "Bodmin Parkway - BOD";
    countries << "Bodorgan - BOR";
    countries << "Bognor Regis - BOG";
    countries << "Bogston - BGS";
    countries << "Bolton - BON";
    countries << "Bolton-on-Dearne - BTD";
    countries << "Bookham - BKA";
    countries << "Bootle (Cumbria) - BOC";
    countries << "Bootle New Strand - BNW";
    countries << "Bootle Oriel Road - BOT";
    countries << "Bordesley - BBS";
    countries << "Borough Green & Wrotham - BRG";
    countries << "Borth - BRH";
    countries << "Bosham - BOH";
    countries << "Boston - BSN";
    countries << "Botley - BOE";
    countries << "Bottesford - BTF";
    countries << "Bourne End - BNE";
    countries << "Bournemouth - BMH";
    countries << "Bournville - BRV";
    countries << "Bow Brickhill - BWB";
    countries << "Bowes Park - BOP";
    countries << "Bowling - BWG";
    countries << "Box Hill & Westhumble - BXW";
    countries << "Bracknell - BCE";
    countries << "Bradford Forster Square - BDQ";
    countries << "Bradford Interchange - BDI";
    countries << "Bradford-on-Avon - BOA";
    countries << "Brading - BDN";
    countries << "Braintree - BTR";
    countries << "Braintree Freeport - BTP";
    countries << "Bramhall - BML";
    countries << "Bramley (Hants) - BMY";
    countries << "Bramley (W Yorks) - BLE";
    countries << "Brampton (Cumbria) - BMP";
    countries << "Brampton (Suffolk) - BRP";
    countries << "Branchton - BCN";
    countries << "Brandon - BND";
    countries << "Branksome - BSM";
    countries << "Braystones (Cumbria) - BYS";
    countries << "Bredbury - BDY";
    countries << "Breich - BRC";
    countries << "Brentford - BFD";
    countries << "Brentwood - BRE";
    countries << "Bricket Wood - BWO";
    countries << "Bridge of Allan - BEA";
    countries << "Bridge of Orchy - BRO";
    countries << "Bridgend - BGN";
    countries << "Bridgeton - BDG";
    countries << "Bridgwater - BWT";
    countries << "Bridlington - BDT";
    countries << "Brierfield - BRF";
    countries << "Brigg - BGG";
    countries << "Brighouse - BGH";
    countries << "Brighton (East Sussex) - BTN";
    countries << "Brimsdown - BMD";
    countries << "Brinnington - BNT";
    countries << "Bristol Parkway - BPW";
    countries << "Bristol Temple Meads - BRI";
    countries << "Brithdir - BHD";
    countries << "Briton Ferry - BNF";
    countries << "Brixton - BRX";
    countries << "Broad Green - BGE";
    countries << "Broadbottom - BDB";
    countries << "Broadstairs - BSR";
    countries << "Brockenhurst - BCU";
    countries << "Brockholes - BHS";
    countries << "Brockley - BCY";
    countries << "Bromborough - BOM";
    countries << "Bromborough Rake - BMR";
    countries << "Bromley Cross (Lancs) - BMC";
    countries << "Bromley North - BMN";
    countries << "Bromley South - BMS";
    countries << "Bromsgrove - BMV";
    countries << "Brondesbury - BSY";
    countries << "Brondesbury Park - BSP";
    countries << "Brookmans Park - BPK";
    countries << "Brookwood - BKO";
    countries << "Broome - BME";
    countries << "Broomfleet - BMF";
    countries << "Brora - BRA";
    countries << "Brough - BUH";
    countries << "Broughty Ferry - BYF";
    countries << "Broxbourne - BXB";
    countries << "Bruce Grove - BCV";
    countries << "Brundall - BDA";
    countries << "Brundall Gardens - BGA";
    countries << "Brunstane - BSU";
    countries << "Brunswick - BRW";
    countries << "Bruton - BRU";
    countries << "Bryn - BYN";
    countries << "Buckenham (Norfolk) - BUC";
    countries << "Buckley - BCK";
    countries << "Bucknell - BUK";
    countries << "Buckshaw Parkway - BSV";
    countries << "Bugle - BGL";
    countries << "Builth Road - BHR";
    countries << "Bulwell - BLW";
    countries << "Bures - BUE";
    countries << "Burgess Hill - BUG";
    countries << "Burley Park - BUY";
    countries << "Burley-in-Wharfedale - BUW";
    countries << "Burnage - BNA";
    countries << "Burneside (Cumbria) - BUD";
    countries << "Burnham (Bucks) - BNM";
    countries << "Burnham-on-Crouch - BUU";
    countries << "Burnley Barracks - BUB";
    countries << "Burnley Central - BNC";
    countries << "Burnley Manchester Road - BYM";
    countries << "Burnside (Strathclyde) - BUI";
    countries << "Burntisland - BTS";
    countries << "Burscough Bridge - BCB";
    countries << "Burscough Junction - BCJ";
    countries << "Bursledon - BUO";
    countries << "Burton Joyce - BUJ";
    countries << "Burton-on-Trent - BUT";
    countries << "Bury St Edmunds - BSE";
    countries << "Busby - BUS";
    countries << "Bush Hill Park - BHK";
    countries << "Bushey - BSH";
    countries << "Butlers Lane - BUL";
    countries << "Buxted - BXD";
    countries << "Buxton - BUX";
    countries << "Byfleet & New Haw - BFN";
    countries << "Bynea - BYE";
    countries << "Cadoxton - CAD";
    countries << "Caergwrle - CGW";
    countries << "Caerphilly - CPH";
    countries << "Caersws - CWS";
    countries << "Caldercruix - CAC";
    countries << "Caldicot - CDT";
    countries << "Caledonian Rd & Barnsbury - CIR";
    countries << "Calstock - CSK";
    countries << "Cam & Dursley - CDU";
    countries << "Camberley - CAM";
    countries << "Camborne - CBN";
    countries << "Cambridge - CBG";
    countries << "Cambridge Heath - CBH";
    countries << "Cambuslang - CBL";
    countries << "Camden Road - CMD";
    countries << "Camelon - CMO";
    countries << "Canada Water - ZCW";
    countries << "Canley - CNL";
    countries << "Cannock - CAO";
    countries << "Canonbury - CNN";
    countries << "Canterbury East - CBE";
    countries << "Canterbury West - CBW";
    countries << "Cantley - CNY";
    countries << "Capenhurst - CPU";
    countries << "Carbis Bay - CBB";
    countries << "Cardenden - CDD";
    countries << "Cardiff Bay - CDB";
    countries << "Cardiff Central - CDF";
    countries << "Cardiff Queen Street - CDQ";
    countries << "Cardonald - CDO";
    countries << "Cardross - CDR";
    countries << "Carfin - CRF";
    countries << "Cark & Cartmel - CAK";
    countries << "Carlisle - CAR";
    countries << "Carlton - CTO";
    countries << "Carluke - CLU";
    countries << "Carmarthen - CMN";
    countries << "Carmyle - CML";
    countries << "Carnforth - CNF";
    countries << "Carnoustie - CAN";
    countries << "Carntyne - CAY";
    countries << "Carpenders Park - CPK";
    countries << "Carrbridge - CAG";
    countries << "Carshalton - CSH";
    countries << "Carshalton Beeches - CSB";
    countries << "Carstairs - CRS";
    countries << "Cartsdyke - CDY";
    countries << "Castle Bar Park - CBP";
    countries << "Castle Cary - CLC";
    countries << "Castleford - CFD";
    countries << "Castleton (Manchester) - CAS";
    countries << "Castleton Moor - CSM";
    countries << "Caterham - CAT";
    countries << "Catford - CTF";
    countries << "Catford Bridge - CFB";
    countries << "Cathays - CYS";
    countries << "Cathcart - CCT";
    countries << "Cattal - CTL";
    countries << "Causeland - CAU";
    countries << "Cefn-y-Bedd - CYB";
    countries << "Chadwell Heath - CTH";
    countries << "Chafford Hundred Lakeside - CFH";
    countries << "Chalfont & Latimer - CFO";
    countries << "Chalkwell - CHW";
    countries << "Chandlers Ford - CFR";
    countries << "Chapel-en-le-Frith - CEF";
    countries << "Chapelton (Devon) - CPN";
    countries << "Chapeltown (South Yorks) - CLN";
    countries << "Chappel & Wakes Colne - CWC";
    countries << "Charing Cross (Glasgow) - CHC";
    countries << "Charing (Kent) - CHG";
    countries << "Charlbury - CBY";
    countries << "Charlton - CTN";
    countries << "Chartham - CRT";
    countries << "Chassen Road - CSR";
    countries << "Chatelherault - CTE";
    countries << "Chatham - CTM";
    countries << "Chathill - CHT";
    countries << "Cheadle Hulme - CHU";
    countries << "Cheam - CHE";
    countries << "Cheddington - CED";
    countries << "Chelford (Cheshire) - CEL";
    countries << "Chelmsford - CHM";
    countries << "Chelsfield - CLD";
    countries << "Cheltenham Spa - CNM";
    countries << "Chepstow - CPW";
    countries << "Cherry Tree - CYT";
    countries << "Chertsey - CHY";
    countries << "Cheshunt - CHN";
    countries << "Chessington North - CSN";
    countries << "Chessington South - CSS";
    countries << "Chester - CTR";
    countries << "Chester Road - CRD";
    countries << "Chesterfield - CHD";
    countries << "Chester-le-Street - CLS";
    countries << "Chestfield & Swalecliffe - CSW";
    countries << "Chetnole - CNO";
    countries << "Chichester - CCH";
    countries << "Chilham - CIL";
    countries << "Chilworth - CHL";
    countries << "Chingford - CHI";
    countries << "Chinley - CLY";
    countries << "Chippenham - CPM";
    countries << "Chipstead - CHP";
    countries << "Chirk - CRK";
    countries << "Chislehurst - CIT";
    countries << "Chiswick - CHK";
    countries << "Cholsey - CHO";
    countries << "Chorley - CRL";
    countries << "Chorleywood - CLW";
    countries << "Christchurch - CHR";
    countries << "Christ's Hospital - CHH";
    countries << "Church & Oswaldtwistle - CTW";
    countries << "Church Fenton - CHF";
    countries << "Church Stretton - CTT";
    countries << "Cilmeri - CIM";
    countries << "City Thameslink - CTK";
    countries << "Clacton-on-Sea - CLT";
    countries << "Clandon - CLA";
    countries << "Clapham High Street - CLP";
    countries << "Clapham Junction - CLJ";
    countries << "Clapham (North Yorkshire) - CPY";
    countries << "Clapton - CPT";
    countries << "Clarbeston Road - CLR";
    countries << "Clarkston - CKS";
    countries << "Claverdon - CLV";
    countries << "Claygate - CLG";
    countries << "Cleethorpes - CLE";
    countries << "Cleland - CEA";
    countries << "Clifton Down - CFN";
    countries << "Clifton (Manchester) - CLI";
    countries << "Clitheroe - CLH";
    countries << "Clock House - CLK";
    countries << "Clunderwen - CUW";
    countries << "Clydebank - CYK";
    countries << "Coatbridge Central - CBC";
    countries << "Coatbridge Sunnyside - CBS";
    countries << "Coatdyke - COA";
    countries << "Cobham & Stoke d'Abernon - CSD";
    countries << "Codsall - CSL";
    countries << "Cogan - CGN";
    countries << "Colchester - COL";
    countries << "Colchester Town - CET";
    countries << "Coleshill Parkway - CEH";
    countries << "Collingham - CLM";
    countries << "Collington - CLL";
    countries << "Colne - CNE";
    countries << "Colwall - CWL";
    countries << "Colwyn Bay - CWB";
    countries << "Combe (Oxon) - CME";
    countries << "Commondale - COM";
    countries << "Congleton - CNG";
    countries << "Conisbrough - CNS";
    countries << "Connel Ferry - CON";
    countries << "Conon Bridge - CBD";
    countries << "Cononley - CEY";
    countries << "Conway Park - CNP";
    countries << "Conwy - CNW";
    countries << "Cooden Beach - COB";
    countries << "Cookham - COO";
    countries << "Cooksbridge - CBR";
    countries << "Coombe Junction Halt - COE";
    countries << "Copplestone - COP";
    countries << "Corbridge - CRB";
    countries << "Corby - COR";
    countries << "Corkerhill - CKH";
    countries << "Corkickle - CKL";
    countries << "Corpach - CPA";
    countries << "Corrour - CRR";
    countries << "Coryton - COY";
    countries << "Coseley - CSY";
    countries << "Cosford - COS";
    countries << "Cosham - CSA";
    countries << "Cottingham - CGM";
    countries << "Cottingley - COT";
    countries << "Coulsdon South - CDS";
    countries << "Coulsdon Town - CDN";
    countries << "Coventry - COV";
    countries << "Cowden (Kent) - CWN";
    countries << "Cowdenbeath - COW";
    countries << "Cradley Heath - CRA";
    countries << "Craigendoran - CGD";
    countries << "Cramlington - CRM";
    countries << "Cranbrook - CBK";
    countries << "Craven Arms - CRV";
    countries << "Crawley - CRW";
    countries << "Crayford - CRY";
    countries << "Crediton - CDI";
    countries << "Cressing (Essex) - CES";
    countries << "Cressington - CSG";
    countries << "Creswell - CWD";
    countries << "Crewe - CRE";
    countries << "Crewkerne - CKN";
    countries << "Crews Hill - CWH";
    countries << "Crianlarich - CNR";
    countries << "Criccieth - CCC";
    countries << "Cricklewood - CRI";
    countries << "Croftfoot - CFF";
    countries << "Crofton Park - CFT";
    countries << "Cromer - CMR";
    countries << "Cromford - CMF";
    countries << "Crookston - CKT";
    countries << "Cross Gates - CRG";
    countries << "Crossflatts - CFL";
    countries << "Crosshill - COI";
    countries << "Crosskeys - CKY";
    countries << "Crossmyloof - CMY";
    countries << "Croston - CSO";
    countries << "Crouch Hill - CRH";
    countries << "Crowborough - COH";
    countries << "Crowhurst - CWU";
    countries << "Crowle - CWE";
    countries << "Crowthorne - CRN";
    countries << "Croy - CRO";
    countries << "Crystal Palace - CYP";
    countries << "Cuddington - CUD";
    countries << "Cuffley - CUF";
    countries << "Culham - CUM";
    countries << "Culrain - CUA";
    countries << "Cumbernauld - CUB";
    countries << "Cupar - CUP";
    countries << "Curriehill - CUH";
    countries << "Cuxton - CUX";
    countries << "Cwmbach - CMH";
    countries << "Cwmbran - CWM";
    countries << "Cynghordy - CYN";
    countries << "Dagenham Dock - DDK";
    countries << "Daisy Hill - DSY";
    countries << "Dalgety Bay - DAG";
    countries << "Dalmally - DAL";
    countries << "Dalmarnock - DAK";
    countries << "Dalmeny - DAM";
    countries << "Dalmuir - DMR";
    countries << "Dalreoch - DLR";
    countries << "Dalry - DLY";
    countries << "Dalston (Cumbria) - DLS";
    countries << "Dalston Junction - DLJ";
    countries << "Dalston Kingsland - DLK";
    countries << "Dalton (Cumbria) - DLT";
    countries << "Dalwhinnie - DLW";
    countries << "Danby - DNY";
    countries << "Danescourt - DCT";
    countries << "Danzey - DZY";
    countries << "Darlington - DAR";
    countries << "Darnall - DAN";
    countries << "Darsham - DSM";
    countries << "Dartford - DFD";
    countries << "Darton - DRT";
    countries << "Darwen - DWN";
    countries << "Datchet - DAT";
    countries << "Davenport - DVN";
    countries << "Dawlish - DWL";
    countries << "Dawlish Warren - DWW";
    countries << "Deal - DEA";
    countries << "Dean (Wilts) - DEN";
    countries << "Deansgate - DGT";
    countries << "Deganwy - DGY";
    countries << "Deighton - DHN";
    countries << "Delamere - DLM";
    countries << "Denby Dale - DBD";
    countries << "Denham - DNM";
    countries << "Denham Golf Club - DGC";
    countries << "Denmark Hill - DMK";
    countries << "Dent - DNT";
    countries << "Denton - DTN";
    countries << "Deptford - DEP";
    countries << "Derby - DBY";
    countries << "Derby Road (Ipswich) - DBR";
    countries << "Devonport (Devon) - DPT";
    countries << "Devonport Dockyard - DOC";
    countries << "Dewsbury - DEW";
    countries << "Didcot Parkway - DID";
    countries << "Digby & Sowton - DIG";
    countries << "Dilton Marsh - DMH";
    countries << "Dinas Powys - DNS";
    countries << "Dinas (Rhondda) - DMG";
    countries << "Dingle Road - DGL";
    countries << "Dingwall - DIN";
    countries << "Dinsdale - DND";
    countries << "Dinting - DTG";
    countries << "Disley - DSL";
    countries << "Diss - DIS";
    countries << "Dodworth - DOD";
    countries << "Dolau - DOL";
    countries << "Doleham - DLH";
    countries << "Dolgarrog - DLG";
    countries << "Dolwyddelan - DWD";
    countries << "Doncaster - DON";
    countries << "Dorchester South - DCH";
    countries << "Dorchester West - DCW";
    countries << "Dore & Totley - DOR";
    countries << "Dorking Deepdene - DPD";
    countries << "Dorking (Main) - DKG";
    countries << "Dorking West - DKT";
    countries << "Dormans - DMS";
    countries << "Dorridge - DDG";
    countries << "Dove Holes - DVH";
    countries << "Dover Priory - DVP";
    countries << "Dovercourt - DVC";
    countries << "Dovey Junction - DVY";
    countries << "Downham Market - DOW";
    countries << "Drayton Green - DRG";
    countries << "Drayton Park - DYP";
    countries << "Drem - DRM";
    countries << "Driffield - DRF";
    countries << "Drigg - DRI";
    countries << "Droitwich Spa - DTW";
    countries << "Dronfield - DRO";
    countries << "Drumchapel - DMC";
    countries << "Drumfrochar - DFR";
    countries << "Drumgelloch - DRU";
    countries << "Drumry - DMY";
    countries << "Dublin Ferryport - DFP";
    countries << "Dublin Port - Stena - DPS";
    countries << "Duddeston - DUD";
    countries << "Dudley Port - DDP";
    countries << "Duffield - DFI";
    countries << "Duirinish - DRN";
    countries << "Duke Street - DST";
    countries << "Dullingham - DUL";
    countries << "Dumbarton Central - DBC";
    countries << "Dumbarton East - DBE";
    countries << "Dumbreck - DUM";
    countries << "Dumfries - DMF";
    countries << "Dumpton Park - DMP";
    countries << "Dunbar - DUN";
    countries << "Dunblane - DBL";
    countries << "Duncraig - DCG";
    countries << "Dundee - DEE";
    countries << "Dunfermline Queen Margaret - DFL";
    countries << "Dunfermline Town - DFE";
    countries << "Dunkeld & Birnam - DKD";
    countries << "Dunlop - DNL";
    countries << "Dunrobin Castle - DNO";
    countries << "Dunston - DOT";
    countries << "Dunton Green - DNG";
    countries << "Durham - DHM";
    countries << "Durrington-on-Sea - DUR";
    countries << "Dyce - DYC";
    countries << "Dyffryn Ardudwy - DYF";
    countries << "Eaglescliffe - EAG";
    countries << "Ealing Broadway - EAL";
    countries << "Earlestown - ERL";
    countries << "Earley - EAR";
    countries << "Earlsfield - EAD";
    countries << "Earlswood (Surrey) - ELD";
    countries << "Earlswood (West Midlands) - EWD";
    countries << "East Croydon - ECR";
    countries << "East Didsbury - EDY";
    countries << "East Dulwich - EDW";
    countries << "East Farleigh - EFL";
    countries << "East Garforth - EGF";
    countries << "East Grinstead - EGR";
    countries << "East Kilbride - EKL";
    countries << "East Malling - EML";
    countries << "East Midlands Parkway - EMD";
    countries << "East Tilbury - ETL";
    countries << "East Worthing - EWR";
    countries << "Eastbourne - EBN";
    countries << "Eastbrook - EBK";
    countries << "Easterhouse - EST";
    countries << "Eastham Rake - ERA";
    countries << "Eastleigh - ESL";
    countries << "Eastrington - EGN";
    countries << "Ebbsfleet International - EBD";
    countries << "Ebbw Vale Parkway - EBV";
    countries << "Eccles (Manchester) - ECC";
    countries << "Eccles Road - ECS";
    countries << "Eccleston Park - ECL";
    countries << "Edale - EDL";
    countries << "Eden Park - EDN";
    countries << "Edenbridge (Kent) - EBR";
    countries << "Edenbridge Town - EBT";
    countries << "Edge Hill - EDG";
    countries << "Edinburgh - EDB";
    countries << "Edinburgh Park - EDP";
    countries << "Edmonton Green - EDR";
    countries << "Effingham Junction - EFF";
    countries << "Eggesford - EGG";
    countries << "Egham - EGH";
    countries << "Egton - EGT";
    countries << "Elephant & Castle - EPH";
    countries << "Elephant & Castle (Underground) - ZEL";
    countries << "Elgin - ELG";
    countries << "Ellesmere Port - ELP";
    countries << "Elmers End - ELE";
    countries << "Elmstead Woods - ESD";
    countries << "Elmswell - ESW";
    countries << "Elsecar - ELR";
    countries << "Elsenham (Essex) - ESM";
    countries << "Elstree & Borehamwood - ELS";
    countries << "Eltham - ELW";
    countries << "Elton & Orston - ELO";
    countries << "Ely - ELY";
    countries << "Emerson Park - EMP";
    countries << "Emsworth - EMS";
    countries << "Enfield Chase - ENC";
    countries << "Enfield Lock - ENL";
    countries << "Enfield Town - ENF";
    countries << "Entwistle - ENT";
    countries << "Epsom Downs - EPD";
    countries << "Epsom (Surrey) - EPS";
    countries << "Erdington - ERD";
    countries << "Eridge - ERI";
    countries << "Erith - ERH";
    countries << "Esher - ESH";
    countries << "Essex Road - EXR";
    countries << "Etchingham - ETC";
    countries << "Euxton Balshaw Lane - EBA";
    countries << "Evesham - EVE";
    countries << "Ewell East - EWE";
    countries << "Ewell West - EWW";
    countries << "Exeter Central - EXC";
    countries << "Exeter St David's - EXD";
    countries << "Exeter St Thomas - EXT";
    countries << "Exhibition Centre (Glasgow) - EXG";
    countries << "Exmouth - EXM";
    countries << "Exton - EXN";
    countries << "Eynsford - EYN";
    countries << "Fairbourne - FRB";
    countries << "Fairfield - FRF";
    countries << "Fairlie - FRL";
    countries << "Fairwater - FRW";
    countries << "Falconwood - FCN";
    countries << "Falkirk Grahamston - FKG";
    countries << "Falkirk High - FKK";
    countries << "Falls of Cruachan - FOC";
    countries << "Falmer - FMR";
    countries << "Falmouth Docks - FAL";
    countries << "Falmouth Town - FMT";
    countries << "Fareham - FRM";
    countries << "Farnborough (Main) - FNB";
    countries << "Farnborough North - FNN";
    countries << "Farncombe - FNC";
    countries << "Farnham - FNH";
    countries << "Farningham Road - FNR";
    countries << "Farnworth - FNW";
    countries << "Farringdon - ZFD";
    countries << "Fauldhouse - FLD";
    countries << "Faversham - FAV";
    countries << "Faygate - FGT";
    countries << "Fazakerley - FAZ";
    countries << "Fearn - FRN";
    countries << "Featherstone - FEA";
    countries << "Felixstowe - FLX";
    countries << "Feltham - FEL";
    countries << "Feniton - FNT";
    countries << "Fenny Stratford - FEN";
    countries << "Fernhill - FER";
    countries << "Ferriby - FRY";
    countries << "Ferryside - FYS";
    countries << "Ffairfach - FFA";
    countries << "Filey - FIL";
    countries << "Filton Abbey Wood - FIT";
    countries << "Finchley Road & Frognal - FNY";
    countries << "Finsbury Park - FPK";
    countries << "Finstock - FIN";
    countries << "Fishbourne (Sussex) - FSB";
    countries << "Fishersgate - FSG";
    countries << "Fishguard & Goodwick - FGW";
    countries << "Fishguard Harbour - FGH";
    countries << "Fiskerton - FSK";
    countries << "Fitzwilliam - FZW";
    countries << "Five Ways - FWY";
    countries << "Fleet - FLE";
    countries << "Flimby - FLM";
    countries << "Flint - FLN";
    countries << "Flitwick - FLT";
    countries << "Flixton - FLI";
    countries << "Flowery Field - FLF";
    countries << "Folkestone Central - FKC";
    countries << "Folkestone West - FKW";
    countries << "Ford - FOD";
    countries << "Forest Gate - FOG";
    countries << "Forest Hill - FOH";
    countries << "Formby - FBY";
    countries << "Forres - FOR";
    countries << "Forsinard - FRS";
    countries << "Fort Matilda - FTM";
    countries << "Fort William - FTW";
    countries << "Four Oaks - FOK";
    countries << "Foxfield - FOX";
    countries << "Foxton - FXN";
    countries << "Frant - FRT";
    countries << "Fratton - FTN";
    countries << "Freshfield - FRE";
    countries << "Freshford - FFD";
    countries << "Frimley - FML";
    countries << "Frinton-on-Sea - FRI";
    countries << "Frizinghall - FZH";
    countries << "Frodsham - FRD";
    countries << "Frome - FRO";
    countries << "Fulwell - FLW";
    countries << "Furness Vale - FNV";
    countries << "Furze Platt - FZP";
    countries << "Gainsborough Central - GNB";
    countries << "Gainsborough Lea Road - GBL";
    countries << "Garelochhead - GCH";
    countries << "Garforth - GRF";
    countries << "Gargrave - GGV";
    countries << "Garrowhill - GAR";
    countries << "Garscadden - GRS";
    countries << "Garsdale - GSD";
    countries << "Garston (Hertfordshire) - GSN";
    countries << "Garswood - GSW";
    countries << "Gartcosh - GRH";
    countries << "Garth (Bridgend) - GMG";
    countries << "Garth (Powys) - GTH";
    countries << "Garve - GVE";
    countries << "Gathurst - GST";
    countries << "Gatley - GTY";
    countries << "Gatwick Airport - GTW";
    countries << "Georgemas Junction - GGJ";
    countries << "Gerrards Cross - GER";
    countries << "Gidea Park - GDP";
    countries << "Giffnock - GFN";
    countries << "Giggleswick - GIG";
    countries << "Gilberdyke - GBD";
    countries << "Gilfach Fargoed - GFF";
    countries << "Gillingham (Dorset) - GIL";
    countries << "Gillingham (Kent) - GLM";
    countries << "Gilshochill - GSC";
    countries << "Gipsy Hill - GIP";
    countries << "Girvan - GIR";
    countries << "Glaisdale - GLS";
    countries << "Glan Conwy - GCW";
    countries << "Glasgow Central - GLC";
    countries << "Glasgow Queen Street - GLQ";
    countries << "Glasshoughton - GLH";
    countries << "Glazebrook - GLZ";
    countries << "Gleneagles - GLE";
    countries << "Glenfinnan - GLF";
    countries << "Glengarnock - GLG";
    countries << "Glenrothes with Thornton - GLT";
    countries << "Glossop - GLO";
    countries << "Gloucester - GCR";
    countries << "Glynde - GLY";
    countries << "Gobowen - GOB";
    countries << "Godalming - GOD";
    countries << "Godley - GDL";
    countries << "Godstone - GDN";
    countries << "Goldthorpe - GOE";
    countries << "Golf Street - GOF";
    countries << "Golspie - GOL";
    countries << "Gomshall - GOM";
    countries << "Goodmayes - GMY";
    countries << "Goole - GOO";
    countries << "Goostrey - GTR";
    countries << "Gordon Hill - GDH";
    countries << "Goring & Streatley - GOR";
    countries << "Goring-by-Sea - GBS";
    countries << "Gorton - GTO";
    countries << "Gospel Oak - GPO";
    countries << "Gourock - GRK";
    countries << "Gowerton - GWN";
    countries << "Goxhill - GOX";
    countries << "Grange Park - GPK";
    countries << "Grange-Over-Sands - GOS";
    countries << "Grangetown (Cardiff) - GTN";
    countries << "Grantham - GRA";
    countries << "Grateley - GRT";
    countries << "Gravelly Hill - GVH";
    countries << "Gravesend - GRV";
    countries << "Grays - GRY";
    countries << "Great Ayton - GTA";
    countries << "Great Bentley - GRB";
    countries << "Great Chesterford - GRC";
    countries << "Great Coates - GCT";
    countries << "Great Malvern - GMV";
    countries << "Great Missenden - GMN";
    countries << "Great Yarmouth - GYM";
    countries << "Green Lane - GNL";
    countries << "Green Road - GNR";
    countries << "Greenbank - GBK";
    countries << "Greenfaulds - GRL";
    countries << "Greenfield - GNF";
    countries << "Greenford - GFD";
    countries << "Greenhithe - GNH";
    countries << "Greenock Central - GKC";
    countries << "Greenock West - GKW";
    countries << "Greenwich - GNW";
    countries << "Gretna Green - GEA";
    countries << "Grimsby Docks - GMD";
    countries << "Grimsby Town - GMB";
    countries << "Grindleford - GRN";
    countries << "Grosmont - GMT";
    countries << "Grove Park - GRP";
    countries << "Guide Bridge - GUI";
    countries << "Guildford - GLD";
    countries << "Guiseley - GSY";
    countries << "Gunnersbury - GUN";
    countries << "Gunnislake - GSL";
    countries << "Gunton - GNT";
    countries << "Gwersyllt - GWE";
    countries << "Gypsy Lane - GYP";
    countries << "Habrough - HAB";
    countries << "Hackbridge - HCB";
    countries << "Hackney Central - HKC";
    countries << "Hackney Downs - HAC";
    countries << "Hackney Wick - HKW";
    countries << "Haddenham & Thame Parkway - HDM";
    countries << "Haddiscoe - HAD";
    countries << "Hadfield - HDF";
    countries << "Hadley Wood - HDW";
    countries << "Hag Fold - HGF";
    countries << "Haggerston - HGG";
    countries << "Hagley - HAG";
    countries << "Hairmyres - HMY";
    countries << "Hale (Manchester) - HAL";
    countries << "Halesworth - HAS";
    countries << "Halewood - HED";
    countries << "Halifax - HFX";
    countries << "Hall Green - HLG";
    countries << "Hall Road - HLR";
    countries << "Halling - HAI";
    countries << "Hall-i'-th'-Wood - HID";
    countries << "Haltwhistle - HWH";
    countries << "Ham Street - HMT";
    countries << "Hamble - HME";
    countries << "Hamilton Central - HNC";
    countries << "Hamilton West - HNW";
    countries << "Hammerton - HMM";
    countries << "Hampden Park (Sussex) - HMD";
    countries << "Hampstead Heath - HDH";
    countries << "Hampton Court - HMC";
    countries << "Hampton (London) - HMP";
    countries << "Hampton Wick - HMW";
    countries << "Hampton-in-Arden - HIA";
    countries << "Hamstead (Birmingham) - HSD";
    countries << "Hamworthy - HAM";
    countries << "Hanborough - HND";
    countries << "Handforth - HTH";
    countries << "Hanwell - HAN";
    countries << "Hapton - HPN";
    countries << "Harlech - HRL";
    countries << "Harlesden - HDN";
    countries << "Harling Road - HRD";
    countries << "Harlington (Beds) - HLN";
    countries << "Harlow Mill - HWM";
    countries << "Harlow Town - HWN";
    countries << "Harold Wood - HRO";
    countries << "Harpenden - HPD";
    countries << "Harrietsham - HRM";
    countries << "Harringay - HGY";
    countries << "Harringay Green Lanes - HRY";
    countries << "Harrington - HRR";
    countries << "Harrogate - HGT";
    countries << "Harrow & Wealdstone - HRW";
    countries << "Harrow-on-the-Hill - HOH";
    countries << "Hartford (Cheshire) - HTF";
    countries << "Hartlebury - HBY";
    countries << "Hartlepool - HPL";
    countries << "Hartwood - HTW";
    countries << "Harwich International - HPQ";
    countries << "Harwich Town - HWC";
    countries << "Haslemere - HSL";
    countries << "Hassocks - HSK";
    countries << "Hastings - HGS";
    countries << "Hatch End - HTE";
    countries << "Hatfield & Stainforth - HFS";
    countries << "Hatfield (Herts) - HAT";
    countries << "Hatfield Peverel - HAP";
    countries << "Hathersage - HSG";
    countries << "Hattersley - HTY";
    countries << "Hatton - HTN";
    countries << "Havant - HAV";
    countries << "Havenhouse - HVN";
    countries << "Haverfordwest - HVF";
    countries << "Hawarden - HWD";
    countries << "Hawarden Bridge - HWB";
    countries << "Hawkhead - HKH";
    countries << "Haydon Bridge - HDB";
    countries << "Haydons Road - HYR";
    countries << "Hayes & Harlington - HAY";
    countries << "Hayes (Kent) - HYS";
    countries << "Hayle - HYL";
    countries << "Haymarket - HYM";
    countries << "Haywards Heath - HHE";
    countries << "Hazel Grove - HAZ";
    countries << "Headcorn - HCN";
    countries << "Headingley - HDY";
    countries << "Headstone Lane - HDL";
    countries << "Heald Green - HDG";
    countries << "Healing - HLI";
    countries << "Heath High Level - HHL";
    countries << "Heath Low Level - HLL";
    countries << "Heathrow Airport Terminal 4 - HAF";
    countries << "Heathrow Airport Terminal 5 - HWV";
    countries << "Heathrow Airport Terminals 1 - 2 and 3 - HXX";
    countries << "Heaton Chapel - HTC";
    countries << "Hebden Bridge - HBD";
    countries << "Heckington - HEC";
    countries << "Hedge End - HDE";
    countries << "Hednesford - HNF";
    countries << "Heighington - HEI";
    countries << "Helensburgh Central - HLC";
    countries << "Helensburgh Upper - HLU";
    countries << "Hellifield - HLD";
    countries << "Helmsdale - HMS";
    countries << "Helsby - HSB";
    countries << "Hemel Hempstead - HML";
    countries << "Hendon - HEN";
    countries << "Hengoed - HNG";
    countries << "Henley-in-Arden - HNL";
    countries << "Henley-on-Thames - HOT";
    countries << "Hensall - HEL";
    countries << "Hereford - HFD";
    countries << "Herne Bay - HNB";
    countries << "Herne Hill - HNH";
    countries << "Hersham - HER";
    countries << "Hertford East - HFE";
    countries << "Hertford North - HFN";
    countries << "Hessle - HES";
    countries << "Heswall - HSW";
    countries << "Hever - HEV";
    countries << "Heworth - HEW";
    countries << "Hexham - HEX";
    countries << "Heyford - HYD";
    countries << "Heysham Port - HHB";
    countries << "High Brooms - HIB";
    countries << "High Street (Glasgow) - HST";
    countries << "High Street Kensington Underground - ZHS";
    countries << "High Wycombe - HWY";
    countries << "Higham (Kent) - HGM";
    countries << "Highams Park - HIP";
    countries << "Highbridge & Burnham - HIG";
    countries << "Highbury & Islington - HHY";
    countries << "Hightown - HTO";
    countries << "Hildenborough - HLB";
    countries << "Hillfoot - HLF";
    countries << "Hillington East - HLE";
    countries << "Hillington West - HLW";
    countries << "Hillside - HIL";
    countries << "Hilsea - HLS";
    countries << "Hinchley Wood - HYW";
    countries << "Hinckley (Leics) - HNK";
    countries << "Hindley - HIN";
    countries << "Hinton Admiral - HNA";
    countries << "Hitchin - HIT";
    countries << "Hither Green - HGR";
    countries << "Hockley - HOC";
    countries << "Hollingbourne - HBN";
    countries << "Holmes Chapel - HCH";
    countries << "Holmwood - HLM";
    countries << "Holton Heath - HOL";
    countries << "Holyhead - HHD";
    countries << "Holytown - HLY";
    countries << "Homerton - HMN";
    countries << "Honeybourne - HYB";
    countries << "Honiton - HON";
    countries << "Honley - HOY";
    countries << "Honor Oak Park - HPA";
    countries << "Hook - HOK";
    countries << "Hooton - HOO";
    countries << "Hope (Derbyshire) - HOP";
    countries << "Hope (Flintshire) - HPE";
    countries << "Hopton Heath - HPT";
    countries << "Horley - HOR";
    countries << "Hornbeam Park - HBP";
    countries << "Hornsey - HRN";
    countries << "Horsforth - HRS";
    countries << "Horsham - HRH";
    countries << "Horsley - HSY";
    countries << "Horton-in-Ribblesdale - HIR";
    countries << "Horwich Parkway - HWI";
    countries << "Hoscar - HSC";
    countries << "Hough Green - HGN";
    countries << "Hounslow - HOU";
    countries << "Hove - HOV";
    countries << "Hoveton & Wroxham - HXM";
    countries << "How Wood (Herts) - HWW";
    countries << "Howden - HOW";
    countries << "Howwood (Renfrewshire) - HOZ";
    countries << "Hoxton - HOX";
    countries << "Hoylake - HYK";
    countries << "Hubberts Bridge - HBB";
    countries << "Hucknall - HKN";
    countries << "Huddersfield - HUD";
    countries << "Hull - HUL";
    countries << "Humphrey Park - HUP";
    countries << "Huncoat - HCT";
    countries << "Hungerford - HGD";
    countries << "Hunmanby - HUB";
    countries << "Huntingdon - HUN";
    countries << "Huntly - HNT";
    countries << "Hunts Cross - HNX";
    countries << "Hurst Green - HUR";
    countries << "Hutton Cranswick - HUT";
    countries << "Huyton - HUY";
    countries << "Hyde Central - HYC";
    countries << "Hyde North - HYT";
    countries << "Hykeham - HKM";
    countries << "Hyndland - HYN";
    countries << "Hythe (Essex) - HYH";
    countries << "IBM Halt - IBM";
    countries << "Ifield - IFI";
    countries << "Ilford - IFD";
    countries << "Ilkley - ILK";
    countries << "Imperial Wharf - IMW";
    countries << "Ince & Elton - INE";
    countries << "Ince (Manchester) - INC";
    countries << "Ingatestone - INT";
    countries << "Insch - INS";
    countries << "Invergordon - IGD";
    countries << "Invergowrie - ING";
    countries << "Inverkeithing - INK";
    countries << "Inverkip - INP";
    countries << "Inverness - INV";
    countries << "Invershin - INH";
    countries << "Inverurie - INR";
    countries << "Ipswich - IPS";
    countries << "Irlam - IRL";
    countries << "Irvine - IRV";
    countries << "Isleworth - ISL";
    countries << "Islip - ISP";
    countries << "Iver - IVR";
    countries << "Ivybridge - IVY";
    countries << "Jewellery Quarter - JEQ";
    countries << "Johnston (Pembs) - JOH";
    countries << "Johnstone (Strathclyde) - JHN";
    countries << "Jordanhill - JOR";
    countries << "Kearsley (Manchester) - KSL";
    countries << "Kearsney (Kent) - KSN";
    countries << "Keighley - KEI";
    countries << "Keith - KEH";
    countries << "Kelvedon - KEL";
    countries << "Kelvindale - KVD";
    countries << "Kemble - KEM";
    countries << "Kempston Hardwick - KMH";
    countries << "Kempton Park Racecourse - KMP";
    countries << "Kemsing - KMS";
    countries << "Kemsley - KML";
    countries << "Kendal - KEN";
    countries << "Kenley - KLY";
    countries << "Kennett - KNE";
    countries << "Kennishead - KNS";
    countries << "Kensal Green - KNL";
    countries << "Kensal Rise - KNR";
    countries << "Kensington Olympia - KPA";
    countries << "Kent House - KTH";
    countries << "Kentish Town - KTN";
    countries << "Kentish Town West - KTW";
    countries << "Kenton - KNT";
    countries << "Kents Bank - KBK";
    countries << "Kettering - KET";
    countries << "Kew Bridge - KWB";
    countries << "Kew Gardens - KWG";
    countries << "Keyham - KEY";
    countries << "Keynsham - KYN";
    countries << "Kidbrooke - KDB";
    countries << "Kidderminster - KID";
    countries << "Kidsgrove - KDG";
    countries << "Kidwelly - KWL";
    countries << "Kilburn High Road - KBN";
    countries << "Kildale - KLD";
    countries << "Kildonan - KIL";
    countries << "Kilgetty - KGT";
    countries << "Kilmarnock - KMK";
    countries << "Kilmaurs - KLM";
    countries << "Kilpatrick - KPT";
    countries << "Kilwinning - KWN";
    countries << "Kinbrace - KBC";
    countries << "Kingham - KGM";
    countries << "Kinghorn - KGH";
    countries << "Kings Langley - KGL";
    countries << "Kings Lynn - KLN";
    countries << "Kings Norton - KNN";
    countries << "Kings Nympton - KGN";
    countries << "Kings Park - KGP";
    countries << "Kings Sutton - KGS";
    countries << "Kingsknowe - KGE";
    countries << "Kingston - KNG";
    countries << "Kingswood - KND";
    countries << "Kingussie - KIN";
    countries << "Kintbury - KIT";
    countries << "Kirby Cross - KBX";
    countries << "Kirk Sandall - KKS";
    countries << "Kirkby (Merseyside) - KIR";
    countries << "Kirkby Stephen - KSW";
    countries << "Kirkby-in-Ashfield - KKB";
    countries << "Kirkby-in-Furness - KBF";
    countries << "Kirkcaldy - KDY";
    countries << "Kirkconnel - KRK";
    countries << "Kirkdale - KKD";
    countries << "Kirkham & Wesham - KKM";
    countries << "Kirkhill - KKH";
    countries << "Kirknewton - KKN";
    countries << "Kirkwood - KWD";
    countries << "Kirton Lindsey - KTL";
    countries << "Kiveton Bridge - KIV";
    countries << "Kiveton Park - KVP";
    countries << "Knaresborough - KNA";
    countries << "Knebworth - KBW";
    countries << "Knighton - KNI";
    countries << "Knockholt - KCK";
    countries << "Knottingley - KNO";
    countries << "Knucklas - KNU";
    countries << "Knutsford - KNF";
    countries << "Kyle of Lochalsh - KYL";
    countries << "Ladybank - LDY";
    countries << "Ladywell - LAD";
    countries << "Laindon - LAI";
    countries << "Lairg - LRG";
    countries << "Lake - LKE";
    countries << "Lakenheath - LAK";
    countries << "Lamphey - LAM";
    countries << "Lanark - LNK";
    countries << "Lancaster - LAN";
    countries << "Lancing - LAC";
    countries << "Landywood - LAW";
    countries << "Langbank - LGB";
    countries << "Langho - LHO";
    countries << "Langley (Berks) - LNY";
    countries << "Langley Green - LGG";
    countries << "Langley Mill - LGM";
    countries << "Langside - LGS";
    countries << "Langwathby - LGW";
    countries << "Langwith-Whaley Thorns - LAG";
    countries << "Lapford - LAP";
    countries << "Lapworth - LPW";
    countries << "Larbert - LBT";
    countries << "Largs - LAR";
    countries << "Larkhall - LRH";
    countries << "Laurencekirk - LAU";
    countries << "Lawrence Hill - LWH";
    countries << "Layton (Lancs) - LAY";
    countries << "Lazonby & Kirkoswald - LZB";
    countries << "Lea Green - LEG";
    countries << "Lea Hall - LEH";
    countries << "Leagrave - LEA";
    countries << "Lealholm - LHM";
    countries << "Leamington Spa - LMS";
    countries << "Leasowe - LSW";
    countries << "Leatherhead - LHD";
    countries << "Ledbury - LED";
    countries << "Lee (London) - LEE";
    countries << "Leeds - LDS";
    countries << "Leicester - LEI";
    countries << "Leigh (Kent) - LIH";
    countries << "Leigh-on-Sea - LES";
    countries << "Leighton Buzzard - LBZ";
    countries << "Lelant - LEL";
    countries << "Lelant Saltings - LTS";
    countries << "Lenham - LEN";
    countries << "Lenzie - LNZ";
    countries << "Leominster - LEO";
    countries << "Letchworth Garden City - LET";
    countries << "Leuchars (for St. Andrews) - LEU";
    countries << "Levenshulme - LVM";
    countries << "Lewes - LWS";
    countries << "Lewisham - LEW";
    countries << "Leyland - LEY";
    countries << "Leyton Midland Road - LEM";
    countries << "Leytonstone High Road - LER";
    countries << "Lichfield City - LIC";
    countries << "Lichfield Trent Valley - LTV";
    countries << "Lidlington - LID";
    countries << "Limehouse - LHS";
    countries << "Lincoln Central - LCN";
    countries << "Lingfield - LFD";
    countries << "Lingwood - LGD";
    countries << "Linlithgow - LIN";
    countries << "Liphook - LIP";
    countries << "Liskeard - LSK";
    countries << "Liss - LIS";
    countries << "Lisvane & Thornhill - LVT";
    countries << "Little Kimble - LTK";
    countries << "Little Sutton - LTT";
    countries << "Littleborough - LTL";
    countries << "Littlehampton - LIT";
    countries << "Littlehaven - LVN";
    countries << "Littleport - LTP";
    countries << "Liverpool Central - LVC";
    countries << "Liverpool James Street - LVJ";
    countries << "Liverpool Lime Street - LIV";
    countries << "Liverpool South Parkway - LPY";
    countries << "Livingston North - LSN";
    countries << "Livingston South - LVG";
    countries << "Llanaber - LLA";
    countries << "Llanbedr - LBR";
    countries << "Llanbister Road - LLT";
    countries << "Llanbradach - LNB";
    countries << "Llandaf - LLN";
    countries << "Llandanwg - LDN";
    countries << "Llandecwyn - LLC";
    countries << "Llandeilo - LLL";
    countries << "Llandovery - LLV";
    countries << "Llandrindod - LLO";
    countries << "Llandudno - LLD";
    countries << "Llandudno Junction - LLJ";
    countries << "Llandybie - LLI";
    countries << "Llanelli - LLE";
    countries << "Llanfairfechan - LLF";
    countries << "Llanfairpwll - LPG";
    countries << "Llangadog - LLG";
    countries << "Llangammarch - LLM";
    countries << "Llangennech - LLH";
    countries << "Llangynllo - LGO";
    countries << "Llanharan - LLR";
    countries << "Llanhilleth - LTH";
    countries << "Llanishen - LLS";
    countries << "Llanrwst - LWR";
    countries << "Llansamlet - LAS";
    countries << "Llantwit Major - LWM";
    countries << "Llanwrda - LNR";
    countries << "Llanwrtyd - LNW";
    countries << "Llwyngwril - LLW";
    countries << "Llwynypia - LLY";
    countries << "Loch Awe - LHA";
    countries << "Loch Eil Outward Bound - LHE";
    countries << "Lochailort - LCL";
    countries << "Locheilside - LCS";
    countries << "Lochgelly - LCG";
    countries << "Lochluichart - LCC";
    countries << "Lochwinnoch - LHW";
    countries << "Lockerbie - LOC";
    countries << "Lockwood - LCK";
    countries << "London Blackfriars - BFR";
    countries << "London Bridge - LBG";
    countries << "London Cannon Street - CST";
    countries << "London Charing Cross - CHX";
    countries << "London Euston - EUS";
    countries << "London Fenchurch Street - FST";
    countries << "London Fields - LOF";
    countries << "London Kings Cross - KGX";
    countries << "London Liverpool Street - LST";
    countries << "London Marylebone - MYB";
    countries << "London Paddington - PAD";
    countries << "London Road (Brighton) - LRB";
    countries << "London Road (Guildford) - LRD";
    countries << "London St Pancras International - STP";
    countries << "London St Pancras (Intl) - SPX";
    countries << "London Victoria - VIC";
    countries << "London Waterloo - WAT";
    countries << "London Waterloo East - WAE";
    countries << "Long Buckby - LBK";
    countries << "Long Eaton - LGE";
    countries << "Long Preston - LPR";
    countries << "Longbeck - LGK";
    countries << "Longbridge - LOB";
    countries << "Longcross - LNG";
    countries << "Longfield - LGF";
    countries << "Longniddry - LND";
    countries << "Longport - LPT";
    countries << "Longton - LGN";
    countries << "Looe - LOO";
    countries << "Lostock - LOT";
    countries << "Lostock Gralam - LTG";
    countries << "Lostock Hall - LOH";
    countries << "Lostwithiel - LOS";
    countries << "Loughborough - LBO";
    countries << "Loughborough Junction - LGJ";
    countries << "Lowdham - LOW";
    countries << "Lower Sydenham - LSY";
    countries << "Lowestoft - LWT";
    countries << "Ludlow - LUD";
    countries << "Luton - LUT";
    countries << "Luton Airport Parkway - LTN";
    countries << "Luxulyan - LUX";
    countries << "Lydney - LYD";
    countries << "Lye (West Midlands) - LYE";
    countries << "Lymington Pier - LYP";
    countries << "Lymington Town - LYT";
    countries << "Lympstone Commando - LYC";
    countries << "Lympstone Village - LYM";
    countries << "Lytham - LTM";
    countries << "Macclesfield - MAC";
    countries << "Machynlleth - MCN";
    countries << "Maesteg - MST";
    countries << "Maesteg (Ewenny Road) - MEW";
    countries << "Maghull - MAG";
    countries << "Maiden Newton - MDN";
    countries << "Maidenhead - MAI";
    countries << "Maidstone Barracks - MDB";
    countries << "Maidstone East - MDE";
    countries << "Maidstone West - MDW";
    countries << "Malden Manor - MAL";
    countries << "Mallaig - MLG";
    countries << "Malton - MLT";
    countries << "Malvern Link - MVL";
    countries << "Manchester Airport - MIA";
    countries << "Manchester Oxford Road - MCO";
    countries << "Manchester Piccadilly - MAN";
    countries << "Manchester United Football Ground - MUF";
    countries << "Manchester Victoria - MCV";
    countries << "Manea - MNE";
    countries << "Manningtree - MNG";
    countries << "Manor Park - MNP";
    countries << "Manor Road - MNR";
    countries << "Manorbier - MRB";
    countries << "Manors - MAS";
    countries << "Mansfield - MFT";
    countries << "Mansfield Woodhouse - MSW";
    countries << "March - MCH";
    countries << "Marden (Kent) - MRN";
    countries << "Margate - MAR";
    countries << "Market Harborough - MHR";
    countries << "Market Rasen - MKR";
    countries << "Markinch - MNC";
    countries << "Marks Tey - MKT";
    countries << "Marlow - MLW";
    countries << "Marple - MPL";
    countries << "Marsden (Yorks) - MSN";
    countries << "Marske - MSK";
    countries << "Marston Green - MGN";
    countries << "Martin Mill - MTM";
    countries << "Martins Heron - MAO";
    countries << "Marton - MTO";
    countries << "Maryhill - MYH";
    countries << "Maryland - MYL";
    countries << "Maryport - MRY";
    countries << "Matlock - MAT";
    countries << "Matlock Bath - MTB";
    countries << "Mauldeth Road - MAU";
    countries << "Maxwell Park - MAX";
    countries << "Maybole - MAY";
    countries << "Maze Hill - MZH";
    countries << "Meadowhall - MHS";
    countries << "Meldreth - MEL";
    countries << "Melksham - MKM";
    countries << "Melton Mowbray - MMO";
    countries << "Melton (Suffolk) - MES";
    countries << "Menheniot - MEN";
    countries << "Menston - MNN";
    countries << "Meols - MEO";
    countries << "Meols Cop - MEC";
    countries << "Meopham - MEP";
    countries << "Merryton - MEY";
    countries << "Merstham - MHM";
    countries << "Merthyr Tydfil - MER";
    countries << "Merthyr Vale - MEV";
    countries << "Metheringham - MGM";
    countries << "MetroCentre - MCE";
    countries << "Mexborough - MEX";
    countries << "Micheldever - MIC";
    countries << "Micklefield - MIK";
    countries << "Middlesbrough - MBR";
    countries << "Middlewood - MDL";
    countries << "Midgham - MDG";
    countries << "Milford Haven - MFH";
    countries << "Milford (Surrey) - MLF";
    countries << "Mill Hill Broadway - MIL";
    countries << "Mill Hill (Lancs) - MLH";
    countries << "Millbrook (Beds) - MLB";
    countries << "Millbrook (Hants) - MBK";
    countries << "Milliken Park - MIN";
    countries << "Millom - MLM";
    countries << "Mills Hill (Manchester) - MIH";
    countries << "Milngavie - MLN";
    countries << "Milton Keynes Central - MKC";
    countries << "Minffordd - MFF";
    countries << "Minster - MSR";
    countries << "Mirfield - MIR";
    countries << "Mistley - MIS";
    countries << "Mitcham Eastfields - MTC";
    countries << "Mitcham Junction - MIJ";
    countries << "Mobberley - MOB";
    countries << "Monifieth - MON";
    countries << "Monks Risborough - MRS";
    countries << "Montpelier - MTP";
    countries << "Montrose - MTS";
    countries << "Moorfields - MRF";
    countries << "Moorgate - MOG";
    countries << "Moorside - MSD";
    countries << "Moorthorpe - MRP";
    countries << "Morar - MRR";
    countries << "Morchard Road - MRD";
    countries << "Morden South - MDS";
    countries << "Morecambe - MCM";
    countries << "Moreton (Dorset) - MTN";
    countries << "Moreton (Merseyside) - MRT";
    countries << "Moreton-in-Marsh - MIM";
    countries << "Morfa Mawddach - MFA";
    countries << "Morley - MLY";
    countries << "Morpeth - MPT";
    countries << "Mortimer - MOR";
    countries << "Mortlake - MTL";
    countries << "Moses Gate - MSS";
    countries << "Moss Side - MOS";
    countries << "Mossley Hill - MSH";
    countries << "Mossley (Manchester) - MSL";
    countries << "Mosspark - MPK";
    countries << "Moston - MSO";
    countries << "Motherwell - MTH";
    countries << "Motspur Park - MOT";
    countries << "Mottingham - MTG";
    countries << "Mottisfont & Dunbridge - DBG";
    countries << "Mouldsworth - MLD";
    countries << "Moulsecoomb - MCB";
    countries << "Mount Florida - MFL";
    countries << "Mount Vernon - MTV";
    countries << "Mountain Ash - MTA";
    countries << "Muir of Ord - MOO";
    countries << "Muirend - MUI";
    countries << "Musselburgh - MUB";
    countries << "Mytholmroyd - MYT";
    countries << "Nafferton - NFN";
    countries << "Nailsea & Backwell - NLS";
    countries << "Nairn - NRN";
    countries << "Nantwich - NAN";
    countries << "Narberth - NAR";
    countries << "Narborough - NBR";
    countries << "Navigation Road - NVR";
    countries << "Neath - NTH";
    countries << "Needham Market - NMT";
    countries << "Neilston - NEI";
    countries << "Nelson - NEL";
    countries << "Neston - NES";
    countries << "Netherfield - NET";
    countries << "Nethertown - NRT";
    countries << "Netley - NTL";
    countries << "New Barnet - NBA";
    countries << "New Beckenham - NBC";
    countries << "New Brighton - NBN";
    countries << "New Clee - NCE";
    countries << "New Cross - NWX";
    countries << "New Cross Gate - NXG";
    countries << "New Cumnock - NCK";
    countries << "New Eltham - NEH";
    countries << "New Holland - NHL";
    countries << "New Hythe - NHE";
    countries << "New Lane - NLN";
    countries << "New Malden - NEM";
    countries << "New Mills Central - NMC";
    countries << "New Mills Newtown - NMN";
    countries << "New Milton - NWM";
    countries << "New Pudsey - NPD";
    countries << "New Southgate - NSG";
    countries << "Newark Castle - NCT";
    countries << "Newark North Gate - NNG";
    countries << "Newbridge - NBE";
    countries << "Newbury - NBY";
    countries << "Newbury Racecourse - NRC";
    countries << "Newcastle - NCL";
    countries << "Newcraighall - NEW";
    countries << "Newhaven Harbour - NVH";
    countries << "Newhaven Town - NVN";
    countries << "Newington - NGT";
    countries << "Newmarket - NMK";
    countries << "Newport (Essex) - NWE";
    countries << "Newport (South Wales) - NWP";
    countries << "Newquay - NQY";
    countries << "Newstead - NSD";
    countries << "Newton Abbot - NTA";
    countries << "Newton Aycliffe - NAY";
    countries << "Newton for Hyde - NWN";
    countries << "Newton (Lanark) - NTN";
    countries << "Newton St Cyres - NTC";
    countries << "Newton-le-Willows - NLW";
    countries << "Newtonmore - NWR";
    countries << "Newton-on-Ayr - NOA";
    countries << "Newtown (Powys) - NWT";
    countries << "Ninian Park - NNP";
    countries << "Nitshill - NIT";
    countries << "Norbiton - NBT";
    countries << "Norbury - NRB";
    countries << "Normans Bay - NSB";
    countries << "Normanton - NOR";
    countries << "North Berwick - NBW";
    countries << "North Camp - NCM";
    countries << "North Dulwich - NDL";
    countries << "North Fambridge - NFA";
    countries << "North Llanrwst - NLR";
    countries << "North Queensferry - NQU";
    countries << "North Road (Darlington) - NRD";
    countries << "North Sheen - NSH";
    countries << "North Walsham - NWA";
    countries << "North Wembley - NWB";
    countries << "Northallerton - NTR";
    countries << "Northampton - NMP";
    countries << "Northfield - NFD";
    countries << "Northfleet - NFL";
    countries << "Northolt Park - NLT";
    countries << "Northumberland Park - NUM";
    countries << "Northwich - NWI";
    countries << "Norton Bridge - NTB";
    countries << "Norwich - NRW";
    countries << "Norwood Junction - NWD";
    countries << "Nottingham - NOT";
    countries << "Nuneaton - NUN";
    countries << "Nunhead - NHD";
    countries << "Nunthorpe - NNT";
    countries << "Nutbourne - NUT";
    countries << "Nutfield - NUF";
    countries << "Oakengates - OKN";
    countries << "Oakham - OKM";
    countries << "Oakleigh Park - OKL";
    countries << "Oban - OBN";
    countries << "Ockendon - OCK";
    countries << "Ockley - OLY";
    countries << "Okehampton - OKE";
    countries << "Old Hill - OHL";
    countries << "Old Roan - ORN";
    countries << "Old Street - OLD";
    countries << "Oldfield Park - OLF";
    countries << "Olton - OLT";
    countries << "Ore - ORE";
    countries << "Ormskirk - OMS";
    countries << "Orpington - ORP";
    countries << "Orrell - ORR";
    countries << "Orrell Park - OPK";
    countries << "Otford - OTF";
    countries << "Oulton Broad North - OUN";
    countries << "Oulton Broad South - OUS";
    countries << "Outwood - OUT";
    countries << "Overpool - OVE";
    countries << "Overton - OVR";
    countries << "Oxenholme Lake District - OXN";
    countries << "Oxford - OXF";
    countries << "Oxshott - OXS";
    countries << "Oxted - OXT";
    countries << "Paddock Wood - PDW";
    countries << "Padgate - PDG";
    countries << "Paignton - PGN";
    countries << "Paisley Canal - PCN";
    countries << "Paisley Gilmour Street - PYG";
    countries << "Paisley St James - PYJ";
    countries << "Palmers Green - PAL";
    countries << "Pangbourne - PAN";
    countries << "Pannal - PNL";
    countries << "Pantyffynnon - PTF";
    countries << "Par - PAR";
    countries << "Parbold - PBL";
    countries << "Park Street - PKT";
    countries << "Parkstone (Dorset) - PKS";
    countries << "Parson Street - PSN";
    countries << "Partick - PTK";
    countries << "Parton - PRN";
    countries << "Patchway - PWY";
    countries << "Patricroft - PAT";
    countries << "Patterton - PTT";
    countries << "Peartree - PEA";
    countries << "Peckham Rye - PMR";
    countries << "Pegswood - PEG";
    countries << "Pemberton - PEM";
    countries << "Pembrey & Burry Port - PBY";
    countries << "Pembroke - PMB";
    countries << "Pembroke Dock - PMD";
    countries << "Penally - PNA";
    countries << "Penarth - PEN";
    countries << "Pencoed - PCD";
    countries << "Pengam - PGM";
    countries << "Penge East - PNE";
    countries << "Penge West - PNW";
    countries << "Penhelig - PHG";
    countries << "Penistone - PNS";
    countries << "Penkridge - PKG";
    countries << "Penmaenmawr - PMW";
    countries << "Penmere - PNM";
    countries << "Penrhiwceiber - PER";
    countries << "Penrhyndeudraeth - PRH";
    countries << "Penrith (North Lakes) - PNR";
    countries << "Penryn (Cornwall) - PYN";
    countries << "Pensarn (Gwynedd) - PES";
    countries << "Penshurst - PHR";
    countries << "Pentre-Bach - PTB";
    countries << "Pen-y-Bont - PNY";
    countries << "Penychain - PNC";
    countries << "Penyffordd - PNF";
    countries << "Penzance - PNZ";
    countries << "Perranwell - PRW";
    countries << "Perry Barr - PRY";
    countries << "Pershore - PSH";
    countries << "Perth - PTH";
    countries << "Peterborough - PBO";
    countries << "Petersfield - PTR";
    countries << "Petts Wood - PET";
    countries << "Pevensey & Westham - PEV";
    countries << "Pevensey Bay - PEB";
    countries << "Pewsey - PEW";
    countries << "Pilning - PIL";
    countries << "Pinhoe - PIN";
    countries << "Pitlochry - PIT";
    countries << "Pitsea - PSE";
    countries << "Pleasington - PLS";
    countries << "Plockton - PLK";
    countries << "Pluckley - PLC";
    countries << "Plumley - PLM";
    countries << "Plumpton - PMP";
    countries << "Plumstead - PLU";
    countries << "Plymouth - PLY";
    countries << "Pokesdown - POK";
    countries << "Polegate - PLG";
    countries << "Polesworth - PSW";
    countries << "Pollokshaws East - PWE";
    countries << "Pollokshaws West - PWW";
    countries << "Pollokshields East - PLE";
    countries << "Pollokshields West - PLW";
    countries << "Polmont - PMT";
    countries << "Polsloe Bridge - POL";
    countries << "Ponders End - PON";
    countries << "Pontarddulais - PTD";
    countries << "Pontefract Baghill - PFR";
    countries << "Pontefract Monkhill - PFM";
    countries << "Pontefract Tanshelf - POT";
    countries << "Pontlottyn - PLT";
    countries << "Pontyclun - PYC";
    countries << "Pont-y-Pant - PYP";
    countries << "Pontypool & New Inn - PPL";
    countries << "Pontypridd - PPD";
    countries << "Poole - POO";
    countries << "Poppleton - POP";
    countries << "Port Glasgow - PTG";
    countries << "Port Sunlight - PSL";
    countries << "Port Talbot Parkway - PTA";
    countries << "Portchester - PTC";
    countries << "Porth - POR";
    countries << "Porthmadog - PTM";
    countries << "Portlethen - PLN";
    countries << "Portslade - PLD";
    countries << "Portsmouth & Southsea - PMS";
    countries << "Portsmouth Arms - PMA";
    countries << "Portsmouth Harbour - PMH";
    countries << "Possilpark & Parkhouse - PPK";
    countries << "Potters Bar - PBR";
    countries << "Poulton-le-Fylde - PFY";
    countries << "Poynton - PYT";
    countries << "Prees - PRS";
    countries << "Prescot - PSC";
    countries << "Prestatyn - PRT";
    countries << "Prestbury - PRB";
    countries << "Preston (Lancs) - PRE";
    countries << "Preston Park - PRP";
    countries << "Prestonpans - PST";
    countries << "Prestwick International Airport - PRA";
    countries << "Prestwick Town - PTW";
    countries << "Priesthill & Darnley - PTL";
    countries << "Princes Risborough - PRR";
    countries << "Prittlewell - PRL";
    countries << "Prudhoe - PRU";
    countries << "Pulborough - PUL";
    countries << "Purfleet - PFL";
    countries << "Purley - PUR";
    countries << "Purley Oaks - PUO";
    countries << "Putney - PUT";
    countries << "Pwllheli - PWL";
    countries << "Pyle - PYL";
    countries << "Quakers Yard - QYD";
    countries << "Queenborough - QBR";
    countries << "Queens Park (Glasgow) - QPK";
    countries << "Queens Park (London) - QPW";
    countries << "Queens Road (Peckham) - QRP";
    countries << "Queenstown Road (Battersea) - QRB";
    countries << "Quintrell Downs - QUI";
    countries << "Radcliffe-on-Trent - RDF";
    countries << "Radlett - RDT";
    countries << "Radley - RAD";
    countries << "Radyr - RDR";
    countries << "Rainford - RNF";
    countries << "Rainham (Essex) - RNM";
    countries << "Rainham (Kent) - RAI";
    countries << "Rainhill - RNH";
    countries << "Ramsgate - RAM";
    countries << "Ramsgreave & Wilpshire - RGW";
    countries << "Rannoch - RAN";
    countries << "Rauceby - RAU";
    countries << "Ravenglass for Eskdale - RAV";
    countries << "Ravensbourne - RVB";
    countries << "Ravensthorpe - RVN";
    countries << "Rawcliffe - RWC";
    countries << "Rayleigh - RLG";
    countries << "Raynes Park - RAY";
    countries << "Reading - RDG";
    countries << "Reading West - RDW";
    countries << "Rectory Road - REC";
    countries << "Redbridge - RDB";
    countries << "Redcar British Steel - RBS";
    countries << "Redcar Central - RCC";
    countries << "Redcar East - RCE";
    countries << "Reddish North - RDN";
    countries << "Reddish South - RDS";
    countries << "Redditch - RDC";
    countries << "Redhill - RDH";
    countries << "Redland - RDA";
    countries << "Redruth - RED";
    countries << "Reedham (Norfolk) - REE";
    countries << "Reedham (Surrey) - RHM";
    countries << "Reigate - REI";
    countries << "Renton - RTN";
    countries << "Retford - RET";
    countries << "Rhiwbina - RHI";
    countries << "Rhoose Cardiff International Airport - RIA";
    countries << "Rhosneigr - RHO";
    countries << "Rhyl - RHL";
    countries << "Rhymney - RHY";
    countries << "Ribblehead - RHD";
    countries << "Rice Lane - RIL";
    countries << "Richmond (London) - RMD";
    countries << "Rickmansworth - RIC";
    countries << "Riddlesdown - RDD";
    countries << "Ridgmont - RID";
    countries << "Riding Mill - RDM";
    countries << "Risca & Pontymister - RCA";
    countries << "Rishton - RIS";
    countries << "Robertsbridge - RBR";
    countries << "Roby - ROB";
    countries << "Rochdale - RCD";
    countries << "Roche - ROC";
    countries << "Rochester - RTR";
    countries << "Rochford - RFD";
    countries << "Rock Ferry - RFY";
    countries << "Rogart - ROG";
    countries << "Rogerstone - ROR";
    countries << "Rolleston - ROL";
    countries << "Roman Bridge - RMB";
    countries << "Romford - RMF";
    countries << "Romiley - RML";
    countries << "Romsey - ROM";
    countries << "Roose - ROO";
    countries << "Rose Grove - RSG";
    countries << "Rose Hill Marple - RSH";
    countries << "Rosyth - ROS";
    countries << "Rotherham Central - RMC";
    countries << "Rotherhithe - ROE";
    countries << "Roughton Road - RNR";
    countries << "Rowlands Castle - RLN";
    countries << "Rowley Regis - ROW";
    countries << "Roy Bridge - RYB";
    countries << "Roydon - RYN";
    countries << "Royston - RYS";
    countries << "Ruabon - RUA";
    countries << "Rufford - RUF";
    countries << "Rugby - RUG";
    countries << "Rugeley Town - RGT";
    countries << "Rugeley Trent Valley - RGL";
    countries << "Runcorn - RUN";
    countries << "Runcorn East - RUE";
    countries << "Ruskington - RKT";
    countries << "Ruswarp - RUS";
    countries << "Rutherglen - RUT";
    countries << "Ryde St Johns Road - RYR";
    countries << "Ryde Esplanade - RYD";
    countries << "Ryde Pier Head - RYP";
    countries << "Ryder Brow - RRB";
    countries << "Rye House - RYH";
    countries << "Rye (Sussex) - RYE";
    countries << "Salford Central - SFD";
    countries << "Salford Crescent - SLD";
    countries << "Salfords (Surrey) - SAF";
    countries << "Salhouse - SAH";
    countries << "Salisbury - SAL";
    countries << "Saltaire - SAE";
    countries << "Saltash - STS";
    countries << "Saltburn - SLB";
    countries << "Saltcoats - SLT";
    countries << "Saltmarshe - SAM";
    countries << "Salwick - SLW";
    countries << "Sampford Courtenay - SMC";
    countries << "Sandal & Agbrigg - SNA";
    countries << "Sandbach - SDB";
    countries << "Sanderstead - SNR";
    countries << "Sandhills - SDL";
    countries << "Sandhurst (Berks) - SND";
    countries << "Sandling - SDG";
    countries << "Sandown - SAN";
    countries << "Sandplace - SDP";
    countries << "Sandwell & Dudley - SAD";
    countries << "Sandwich - SDW";
    countries << "Sandy - SDY";
    countries << "Sankey for Penketh - SNK";
    countries << "Sanquhar - SQH";
    countries << "Sarn - SRR";
    countries << "Saundersfoot - SDF";
    countries << "Saunderton - SDR";
    countries << "Sawbridgeworth - SAW";
    countries << "Saxilby - SXY";
    countries << "Saxmundham - SAX";
    countries << "Scarborough - SCA";
    countries << "Scotscalder - SCT";
    countries << "Scotstounhill - SCH";
    countries << "Scunthorpe - SCU";
    countries << "Sea Mills - SML";
    countries << "Seaford (Sussex) - SEF";
    countries << "Seaforth & Litherland - SFL";
    countries << "Seaham - SEA";
    countries << "Seamer - SEM";
    countries << "Seascale - SSC";
    countries << "Seaton Carew - SEC";
    countries << "Seer Green & Jordans - SRG";
    countries << "Selby - SBY";
    countries << "Selhurst - SRS";
    countries << "Sellafield - SEL";
    countries << "Selling - SEG";
    countries << "Selly Oak - SLY";
    countries << "Settle - SET";
    countries << "Seven Kings - SVK";
    countries << "Seven Sisters - SVS";
    countries << "Sevenoaks - SEV";
    countries << "Severn Beach - SVB";
    countries << "Severn Tunnel Junction - STJ";
    countries << "Shadwell - SDE";
    countries << "Shalford (Surrey) - SFR";
    countries << "Shanklin - SHN";
    countries << "Shawford - SHW";
    countries << "Shawlands - SHL";
    countries << "Sheerness-on-Sea - SSS";
    countries << "Sheffield - SHF";
    countries << "Shelford (Cambs) - SED";
    countries << "Shenfield - SNF";
    countries << "Shenstone - SEN";
    countries << "Shepherd's Bush - SPB";
    countries << "Shepherds Well - SPH";
    countries << "Shepley - SPY";
    countries << "Shepperton - SHP";
    countries << "Shepreth - STH";
    countries << "Sherborne - SHE";
    countries << "Sherburn-in-Elmet - SIE";
    countries << "Sheringham - SHM";
    countries << "Shettleston - SLS";
    countries << "Shieldmuir - SDM";
    countries << "Shifnal - SFN";
    countries << "Shildon - SHD";
    countries << "Shiplake - SHI";
    countries << "Shipley (Yorks) - SHY";
    countries << "Shippea Hill - SPP";
    countries << "Shipton - SIP";
    countries << "Shirebrook - SHB";
    countries << "Shirehampton - SHH";
    countries << "Shireoaks - SRO";
    countries << "Shirley - SRL";
    countries << "Shoeburyness - SRY";
    countries << "Sholing - SHO";
    countries << "Shoreditch High Street - SDC";
    countries << "Shoreham (Kent) - SEH";
    countries << "Shoreham-by-Sea - SSE";
    countries << "Shortlands - SRT";
    countries << "Shotton - SHT";
    countries << "Shotts - SHS";
    countries << "Shrewsbury - SHR";
    countries << "Sidcup - SID";
    countries << "Sileby - SIL";
    countries << "Silecroft - SIC";
    countries << "Silkstone Common - SLK";
    countries << "Silver Street - SLV";
    countries << "Silverdale - SVR";
    countries << "Singer - SIN";
    countries << "Sittingbourne - SIT";
    countries << "Skegness - SKG";
    countries << "Skewen - SKE";
    countries << "Skipton - SKI";
    countries << "Slade Green - SGR";
    countries << "Slaithwaite - SWT";
    countries << "Slateford - SLA";
    countries << "Sleaford - SLR";
    countries << "Sleights - SLH";
    countries << "Slough - SLO";
    countries << "Small Heath - SMA";
    countries << "Smallbrook Junction - SAB";
    countries << "Smethwick Galton Bridge - SGB";
    countries << "Smethwick Rolfe Street - SMR";
    countries << "Smithy Bridge - SMB";
    countries << "Snaith - SNI";
    countries << "Snodland - SDA";
    countries << "Snowdown - SWO";
    countries << "Sole Street - SOR";
    countries << "Solihull - SOL";
    countries << "Somerleyton - SYT";
    countries << "South Acton - SAT";
    countries << "South Bank - SBK";
    countries << "South Bermondsey - SBM";
    countries << "South Croydon - SCY";
    countries << "South Elmsall - SES";
    countries << "South Greenford - SGN";
    countries << "South Gyle - SGL";
    countries << "South Hampstead - SOH";
    countries << "South Kenton - SOK";
    countries << "South Merton - SMO";
    countries << "South Milford - SOM";
    countries << "South Ruislip - SRU";
    countries << "South Tottenham - STO";
    countries << "South Wigston - SWS";
    countries << "South Woodham Ferrers - SOF";
    countries << "Southall - STL";
    countries << "Southampton Airport Parkway - SOA";
    countries << "Southampton Central - SOU";
    countries << "Southbourne - SOB";
    countries << "Southbury - SBU";
    countries << "Southease - SEE";
    countries << "Southend Airport - SIA";
    countries << "Southend Central - SOC";
    countries << "Southend East - SOE";
    countries << "Southend Victoria - SOV";
    countries << "Southminster - SMN";
    countries << "Southport - SOP";
    countries << "Southwick - SWK";
    countries << "Sowerby Bridge - SOW";
    countries << "Spalding - SPA";
    countries << "Spean Bridge - SBR";
    countries << "Spital - SPI";
    countries << "Spondon - SPO";
    countries << "Spooner Row - SPN";
    countries << "Spring Road - SRI";
    countries << "Springburn - SPR";
    countries << "Springfield - SPF";
    countries << "Squires Gate - SQU";
    countries << "St Albans - SAC";
    countries << "St Albans Abbey - SAA";
    countries << "St Andrews Road - SAR";
    countries << "St Annes-on-Sea - SAS";
    countries << "St Austell - SAU";
    countries << "St Bees - SBS";
    countries << "St Budeaux Ferry Road - SBF";
    countries << "St Budeaux Victoria Road - SBV";
    countries << "St Columb Road - SCR";
    countries << "St Denys - SDN";
    countries << "St Erth - SER";
    countries << "St Germans - SGM";
    countries << "St Helens Central - SNH";
    countries << "St Helens Junction - SHJ";
    countries << "St Helier (Surrey) - SIH";
    countries << "St Ives (Cornwall) - SIV";
    countries << "St James Park (Exeter) - SJP";
    countries << "St James Street (Walthamstow) - SJS";
    countries << "St Johns (London) - SAJ";
    countries << "St Keyne Wishing Well Halt - SKN";
    countries << "St Leonards Warrior Square - SLQ";
    countries << "St Margarets (Herts) - SMT";
    countries << "St Margarets (London) - SMG";
    countries << "St Mary Cray - SMY";
    countries << "St Michaels - STM";
    countries << "St Neots - SNO";
    countries << "Stafford - STA";
    countries << "Staines - SNS";
    countries << "Stallingborough - SLL";
    countries << "Stalybridge - SYB";
    countries << "Stamford Hill - SMH";
    countries << "Stamford (Lincs) - SMD";
    countries << "Stanford-le-Hope - SFO";
    countries << "Stanlow & Thornton - SNT";
    countries << "Stansted Airport - SSD";
    countries << "Stansted Mountfitchet - SST";
    countries << "Staplehurst - SPU";
    countries << "Stapleton Road - SRD";
    countries << "Starbeck - SBE";
    countries << "Starcross - SCS";
    countries << "Staveley (Cumbria) - SVL";
    countries << "Stechford - SCF";
    countries << "Steeton & Silsden - SON";
    countries << "Stepps - SPS";
    countries << "Stevenage - SVG";
    countries << "Stevenston - STV";
    countries << "Stewartby - SWR";
    countries << "Stewarton - STT";
    countries << "Stirling - STG";
    countries << "Stockport - SPT";
    countries << "Stocksfield - SKS";
    countries << "Stocksmoor - SSM";
    countries << "Stockton - STK";
    countries << "Stoke Mandeville - SKM";
    countries << "Stoke Newington - SKW";
    countries << "Stoke-on-Trent - SOT";
    countries << "Stone Crossing - SCG";
    countries << "Stone (Staffs) - SNE";
    countries << "Stonebridge Park - SBP";
    countries << "Stonegate - SOG";
    countries << "Stonehaven - STN";
    countries << "Stonehouse - SHU";
    countries << "Stoneleigh - SNL";
    countries << "Stourbridge Junction - SBJ";
    countries << "Stourbridge Town - SBT";
    countries << "Stowmarket - SMK";
    countries << "Stranraer - STR";
    countries << "Stratford International - SFA";
    countries << "Stratford (London) - SRA";
    countries << "Stratford-upon-Avon - SAV";
    countries << "Stratford-upon-Avon Parkway - STY";
    countries << "Strathcarron - STC";
    countries << "Strawberry Hill - STW";
    countries << "Streatham Common - SRC";
    countries << "Streatham Hill - SRH";
    countries << "Streatham(Greater London) - STE";
    countries << "Streethouse - SHC";
    countries << "Strines - SRN";
    countries << "Stromeferry - STF";
    countries << "Strood (Kent) - SOO";
    countries << "Stroud (Gloucs) - STD";
    countries << "Sturry - STU";
    countries << "Styal - SYA";
    countries << "Sudbury & Harrow Road - SUD";
    countries << "Sudbury Hill Harrow - SDH";
    countries << "Sudbury (Suffolk) - SUY";
    countries << "Sugar Loaf - SUG";
    countries << "Summerston - SUM";
    countries << "Sunbury - SUU";
    countries << "Sunderland - SUN";
    countries << "Sundridge Park - SUP";
    countries << "Sunningdale - SNG";
    countries << "Sunnymeads - SNY";
    countries << "Surbiton - SUR";
    countries << "Surrey Quays - SQE";
    countries << "Sutton Coldfield - SUT";
    countries << "Sutton Common - SUC";
    countries << "Sutton Parkway - SPK";
    countries << "Sutton (Surrey) - SUO";
    countries << "Swale - SWL";
    countries << "Swanley - SAY";
    countries << "Swanscombe - SWM";
    countries << "Swansea - SWA";
    countries << "Swanwick - SNW";
    countries << "Sway - SWY";
    countries << "Swaythling - SWG";
    countries << "Swinderby - SWD";
    countries << "Swindon (Wilts) - SWI";
    countries << "Swineshead - SWE";
    countries << "Swinton (Manchester) - SNN";
    countries << "Swinton (South Yorks) - SWN";
    countries << "Sydenham Hill - SYH";
    countries << "Sydenham (London) - SYD";
    countries << "Syon Lane - SYL";
    countries << "Syston - SYS";
    countries << "Tackley - TAC";
    countries << "Tadworth - TAD";
    countries << "Taffs Well - TAF";
    countries << "Tain - TAI";
    countries << "Talsarnau - TAL";
    countries << "Talybont - TLB";
    countries << "Tal-y-Cafn - TLC";
    countries << "Tame Bridge Parkway - TAB";
    countries << "Tamworth - TAM";
    countries << "Taplow - TAP";
    countries << "Tattenham Corner - TAT";
    countries << "Taunton - TAU";
    countries << "Taynuilt - TAY";
    countries << "Teddington - TED";
    countries << "Tees-side Airport - TEA";
    countries << "Teignmouth - TGM";
    countries << "Telford Central - TFC";
    countries << "Templecombe - TMC";
    countries << "Tenby - TEN";
    countries << "Teynham - TEY";
    countries << "Thames Ditton - THD";
    countries << "Thatcham - THA";
    countries << "Thatto Heath - THH";
    countries << "The Hawthorns - THW";
    countries << "The Lakes (Warks) - TLK";
    countries << "Theale - THE";
    countries << "Theobalds Grove - TEO";
    countries << "Thetford - TTF";
    countries << "Thirsk - THI";
    countries << "Thornaby - TBY";
    countries << "Thorne North - TNN";
    countries << "Thorne South - TNS";
    countries << "Thornford - THO";
    countries << "Thornliebank - THB";
    countries << "Thornton Abbey - TNA";
    countries << "Thornton Heath - TTH";
    countries << "Thorntonhall - THT";
    countries << "Thorpe Bay - TPB";
    countries << "Thorpe Culvert - TPC";
    countries << "Thorpe-le-Soken - TLS";
    countries << "Three Bridges - TBD";
    countries << "Three Oaks - TOK";
    countries << "Thurgarton - THU";
    countries << "Thurnscoe - THC";
    countries << "Thurso - THS";
    countries << "Thurston - TRS";
    countries << "Tilbury Town - TIL";
    countries << "Tile Hill - THL";
    countries << "Tilehurst - TLH";
    countries << "Tipton - TIP";
    countries << "Tir-Phil - TIR";
    countries << "Tisbury - TIS";
    countries << "Tiverton Parkway - TVP";
    countries << "Todmorden - TOD";
    countries << "Tolworth - TOL";
    countries << "Ton Pentre - TPN";
    countries << "Tonbridge - TON";
    countries << "Tondu - TDU";
    countries << "Tonfanau - TNF";
    countries << "Tonypandy - TNP";
    countries << "Tooting - TOO";
    countries << "Topsham - TOP";
    countries << "Torquay - TQY";
    countries << "Torre - TRR";
    countries << "Totnes - TOT";
    countries << "Tottenham Hale - TOM";
    countries << "Totton - TTN";
    countries << "Town Green - TWN";
    countries << "Trafford Park - TRA";
    countries << "Trefforest - TRF";
    countries << "Trefforest Estate - TRE";
    countries << "Trehafod - TRH";
    countries << "Treherbert - TRB";
    countries << "Treorchy - TRY";
    countries << "Trimley - TRM";
    countries << "Tring - TRI";
    countries << "Troed-y-rhiw - TRD";
    countries << "Troon - TRN";
    countries << "Trowbridge - TRO";
    countries << "Truro - TRU";
    countries << "Tulloch - TUL";
    countries << "Tulse Hill - TUH";
    countries << "Tunbridge Wells - TBW";
    countries << "Turkey Street - TUR";
    countries << "Tutbury & Hatton - TUT";
    countries << "Twickenham - TWI";
    countries << "Twyford - TWY";
    countries << "Ty Croes - TYC";
    countries << "Ty Glas - TGS";
    countries << "Tygwyn - TYG";
    countries << "Tyndrum Lower - TYL";
    countries << "Tyseley - TYS";
    countries << "Tywyn - TYW";
    countries << "Uckfield - UCK";
    countries << "Uddingston - UDD";
    countries << "Ulceby - ULC";
    countries << "Ulleskelf - ULL";
    countries << "Ulverston - ULV";
    countries << "Umberleigh - UMB";
    countries << "University (Birmingham) - UNI";
    countries << "Uphall - UHA";
    countries << "Upholland - UPL";
    countries << "Upminster - UPM";
    countries << "Upper Halliford - UPH";
    countries << "Upper Holloway - UHL";
    countries << "Upper Tyndrum - UTY";
    countries << "Upper Warlingham - UWL";
    countries << "Upton (Merseyside) - UPT";
    countries << "Upwey - UPW";
    countries << "Urmston - URM";
    countries << "Uttoxeter - UTT";
    countries << "Valley - VAL";
    countries << "Vauxhall - VXH";
    countries << "Virginia Water - VIR";
    countries << "Waddon - WDO";
    countries << "Wadhurst - WAD";
    countries << "Wainfleet - WFL";
    countries << "Wakefield Kirkgate - WKK";
    countries << "Wakefield Westgate - WKF";
    countries << "Walkden - WKD";
    countries << "Wallasey Grove Road - WLG";
    countries << "Wallasey Village - WLV";
    countries << "Wallington - WLT";
    countries << "Wallyford - WAF";
    countries << "Walmer - WAM";
    countries << "Walsall - WSL";
    countries << "Walsden - WDN";
    countries << "Waltham Cross - WLC";
    countries << "Walthamstow Central - WHC";
    countries << "Walthamstow Queen's Road - WMW";
    countries << "Walton (Merseyside) - WAO";
    countries << "Walton-on-Thames - WAL";
    countries << "Walton-on-the-Naze - WON";
    countries << "Wanborough - WAN";
    countries << "Wandsworth Common - WSW";
    countries << "Wandsworth Road - WWR";
    countries << "Wandsworth Town - WNT";
    countries << "Wanstead Park - WNP";
    countries << "Wapping - WPE";
    countries << "Warblington - WBL";
    countries << "Ware (Herts) - WAR";
    countries << "Wareham (Dorset) - WRM";
    countries << "Wargrave - WGV";
    countries << "Warminster - WMN";
    countries << "Warnham - WNH";
    countries << "Warrington Bank Quay - WBQ";
    countries << "Warrington Central - WAC";
    countries << "Warwick - WRW";
    countries << "Warwick Parkway - WRP";
    countries << "Water Orton - WTO";
    countries << "Waterbeach - WBC";
    countries << "Wateringbury - WTR";
    countries << "Waterloo (Merseyside) - WLO";
    countries << "Watford High Street - WFH";
    countries << "Watford Junction - WFJ";
    countries << "Watford North - WFN";
    countries << "Watlington - WTG";
    countries << "Watton-at-Stone - WAS";
    countries << "Waun-Gron Park - WNG";
    countries << "Wavertree Technology Park - WAV";
    countries << "Wedgwood - WED";
    countries << "Weeley - WEE";
    countries << "Weeton - WET";
    countries << "Welham Green - WMG";
    countries << "Welling - WLI";
    countries << "Wellingborough - WEL";
    countries << "Wellington (Shropshire) - WLN";
    countries << "Welshpool - WLP";
    countries << "Welwyn Garden City - WGC";
    countries << "Welwyn North - WLW";
    countries << "Wem - WEM";
    countries << "Wembley Central - WMB";
    countries << "Wembley Stadium - WCX";
    countries << "Wemyss Bay - WMS";
    countries << "Wendover - WND";
    countries << "Wennington - WNN";
    countries << "West Allerton - WSA";
    countries << "West Brompton - WBP";
    countries << "West Byfleet - WBY";
    countries << "West Calder - WCL";
    countries << "West Croydon - WCY";
    countries << "West Drayton - WDT";
    countries << "West Dulwich - WDU";
    countries << "West Ealing - WEA";
    countries << "West Ham - WEH";
    countries << "West Hampstead - WHD";
    countries << "West Hampstead Thameslink - WHP";
    countries << "West Horndon - WHR";
    countries << "West Kilbride - WKB";
    countries << "West Kirby - WKI";
    countries << "West Malling - WMA";
    countries << "West Norwood - WNW";
    countries << "West Ruislip - WRU";
    countries << "West Runton - WRN";
    countries << "West St Leonards - WLD";
    countries << "West Sutton - WSU";
    countries << "West Wickham - WWI";
    countries << "West Worthing - WWO";
    countries << "Westbury (Wilts) - WSB";
    countries << "Westcliff - WCF";
    countries << "Westcombe Park - WCB";
    countries << "Westenhanger - WHA";
    countries << "Wester Hailes - WTA";
    countries << "Westerfield - WFI";
    countries << "Westerton - WES";
    countries << "Westgate-on-Sea - WGA";
    countries << "Westhoughton - WHG";
    countries << "Weston Milton - WNM";
    countries << "Weston-super-Mare - WSM";
    countries << "Wetheral - WRL";
    countries << "Weybridge - WYB";
    countries << "Weymouth - WEY";
    countries << "Whaley Bridge - WBR";
    countries << "Whalley (Lancs) - WHE";
    countries << "Whatstandwell - WTS";
    countries << "Whifflet - WFF";
    countries << "Whimple - WHM";
    countries << "Whinhill - WNL";
    countries << "Whiston - WHN";
    countries << "Whitby - WTB";
    countries << "Whitchurch (Cardiff) - WHT";
    countries << "Whitchurch (Hants) - WCH";
    countries << "Whitchurch (Shropshire) - WTC";
    countries << "White Hart Lane - WHL";
    countries << "White Notley - WNY";
    countries << "Whitechapel - ZWL";
    countries << "Whitecraigs - WCR";
    countries << "Whitehaven - WTH";
    countries << "Whitland - WTL";
    countries << "Whitley Bridge - WBD";
    countries << "Whitlocks End - WTE";
    countries << "Whitstable - WHI";
    countries << "Whittlesea - WLE";
    countries << "Whittlesford Parkway - WLF";
    countries << "Whitton (London) - WTN";
    countries << "Whitwell (Derbyshire) - WWL";
    countries << "Whyteleafe - WHY";
    countries << "Whyteleafe South - WHS";
    countries << "Wick - WCK";
    countries << "Wickford - WIC";
    countries << "Wickham Market - WCM";
    countries << "Widdrington - WDD";
    countries << "Widnes - WID";
    countries << "Widney Manor - WMR";
    countries << "Wigan North Western - WGN";
    countries << "Wigan Wallgate - WGW";
    countries << "Wigton - WGT";
    countries << "Wildmill - WMI";
    countries << "Willesden Junction - WIJ";
    countries << "Williamwood - WLM";
    countries << "Willington - WIL";
    countries << "Wilmcote - WMC";
    countries << "Wilmslow - WML";
    countries << "Wilnecote (Staffs) - WNE";
    countries << "Wimbledon - WIM";
    countries << "Wimbledon Chase - WBO";
    countries << "Winchelsea - WSE";
    countries << "Winchester - WIN";
    countries << "Winchfield - WNF";
    countries << "Winchmore Hill - WIH";
    countries << "Windermere - WDM";
    countries << "Windsor & Eton Central - WNC";
    countries << "Windsor & Eton Riverside - WNR";
    countries << "Winnersh - WNS";
    countries << "Winnersh Triangle - WTI";
    countries << "Winsford - WSF";
    countries << "Wishaw - WSH";
    countries << "Witham - WTM";
    countries << "Witley - WTY";
    countries << "Witton (West Midlands) - WTT";
    countries << "Wivelsfield - WVF";
    countries << "Wivenhoe - WIV";
    countries << "Woburn Sands - WOB";
    countries << "Woking - WOK";
    countries << "Wokingham - WKM";
    countries << "Woldingham - WOH";
    countries << "Wolverhampton - WVH";
    countries << "Wolverton - WOL";
    countries << "Wombwell - WOM";
    countries << "Wood End - WDE";
    countries << "Wood Street - WST";
    countries << "Woodbridge - WDB";
    countries << "Woodgrange Park - WGR";
    countries << "Woodhall - WDL";
    countries << "Woodhouse - WDH";
    countries << "Woodlesford - WDS";
    countries << "Woodley - WLY";
    countries << "Woodmansterne - WME";
    countries << "Woodsmoor - WSR";
    countries << "Wool - WOO";
    countries << "Woolston - WLS";
    countries << "Woolwich Arsenal - WWA";
    countries << "Woolwich Dockyard - WWD";
    countries << "Wootton Wawen - WWW";
    countries << "Worcester Foregate Street - WOF";
    countries << "Worcester Park - WCP";
    countries << "Worcester Shrub Hill - WOS";
    countries << "Workington - WKG";
    countries << "Worksop - WRK";
    countries << "Worle - WOR";
    countries << "Worplesdon - WPL";
    countries << "Worstead - WRT";
    countries << "Worthing - WRH";
    countries << "Wrabness - WRB";
    countries << "Wraysbury - WRY";
    countries << "Wrenbury - WRE";
    countries << "Wressle - WRS";
    countries << "Wrexham Central - WXC";
    countries << "Wrexham General - WRX";
    countries << "Wye - WYE";
    countries << "Wylam - WYM";
    countries << "Wylde Green - WYL";
    countries << "Wymondham - WMD";
    countries << "Wythall - WYT";
    countries << "Yalding - YAL";
    countries << "Yardley Wood - YRD";
    countries << "Yarm - YRM";
    countries << "Yate - YAE";
    countries << "Yatton - YAT";
    countries << "Yeoford - YEO";
    countries << "Yeovil Junction - YVJ";
    countries << "Yeovil Pen Mill - YVP";
    countries << "Yetminster - YET";
    countries << "Ynyswen - YNW";
    countries << "Yoker - YOK";
    countries << "York - YRK";
    countries << "Yorton - YRT";
    countries << "Ystrad Mynach - YSM";
    countries << "Ystrad Rhondda - YSR";

    _roles[Qt::DisplayRole] = "text";
}

int TestModel::rowCount(const QModelIndex &parent) const
{
    return countries.size();
}

QVariant TestModel::data(const QModelIndex &index, int role) const
{
    return countries[index.row()];
}
